### ISSUE TITLE
add open cycle map in the predefined maps

### ISSUE THREAD

**Issue by gerald2545** [3liz/lizmap-plugin#109]
need opencyclemap for a project.
Add the option :
![image](https://user-images.githubusercontent.com/10177830/43040407-6804d62a-8d43-11e8-9492-4ec7bb54fc99.png)

if you agree with the terms, order....I will create a PR

**Comment by gerald2545** [comment]
cf https://github.com/3liz/lizmap-web-client/issues/440

**Comment by rldhont** [comment]
Fixed by #110
