### ISSUE TITLE
Issue when trying to configure popup on a project layer

### ISSUE THREAD

**Issue by sylsta** [3liz/lizmap-plugin#111]
![screenshot_20180822_183104](https://user-images.githubusercontent.com/19348327/44477000-f5f24c80-a628-11e8-9ddf-f5cc9d0efb10.png)

The problem can be solved by applying the joint patch. 
Cheers.

[Enable_popup_configuration_of_a_project_layer_(Layers_panel).zip](https://github.com/3liz/lizmap-plugin/files/2311162/Enable_popup_configuration_of_a_project_layer_.Layers_panel.zip)

**Comment by gioman** [comment]
@sylsta @rldhont I confirm the patch fixes the error.

**Comment by sylsta** [comment]
But it was a quick'n'durty one. 
I've took time to modifiy with less new import.
Cheers.

[Enable_popup_configuration_of_a_project_layer_(Layers_panel)_v2.zip](https://github.com/3liz/lizmap-plugin/files/2345989/Enable_popup_configuration_of_a_project_layer_.Layers_panel._v2.zip)

**Comment by sylsta** [comment]
But it was a quick and durty patch. 
This one limits new imports.
All the best. 

[Enable_popup_configuration_of_a_project_layer_(Layers_panel)_V2.zip](https://github.com/3liz/lizmap-plugin/files/2345999/Enable_popup_configuration_of_a_project_layer_.Layers_panel._V2.zip)

**Comment by Gustry** [comment]
This has been fixed in master
