### ISSUE TITLE
QGIS 2.18.23 / LIZMAP Plugin (qgis2) - Locate by Layer

### ISSUE THREAD

**Issue by opbernardo** [3liz/lizmap-plugin#115]
Hi,

I have installed in my computer "Windows 7, 64 Bit", Qgis 2.18.23 from (OSGeo4W), "Lizmap web client 2.12.7", and "lizmap-plugin-qgis2" (lm) om my folder (C:\OSGeo4W\apache\htdocs\lm...).

In browser "http://localhost/lm/lizmap/www/index.php/view/map/?repository=internet&project=teste_qgis", when I select from (Locating) a District and City (Mirandela), go to another place...

Am I doing something wrong?

Thank you for your help.

Best regards.

Orlando

**Comment by Gustry** [comment]
This seems an issue with Lizmap web client, not with Lizmap QGIS plugin.

Do you still confirm the issue?

**Comment by Gustry** [comment]
I'm closing for lacking of feedbacks. Feel free to reopen if necessary or a new ticket.
