### ISSUE TITLE
Remove `External Lizmap layers` from Base layer tab?

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-plugin#121]
According to the manual, the option is now replaced by embedding layers. Better remove it from the plugin to avoid confusion?

**Comment by Gustry** [comment]
@mdouchin Can we hide this section if the CFG doesn't contain any info?
And only display it if the CFG file is not empty.

Then we should add a warning to make it decprecated. It's indeed confusing to have this option and you don't read the documentation, users have no idea that there is another way to do it.

**Comment by mdouchin** [comment]
+1 for me

**Comment by Gustry** [comment]
Ok, it's done, I will keep this ticket open when we will drop this panel for Lizmap 4.

**Comment by Gustry** [comment]
Side note, when removing the external baselayer panel, we will be able to switch the base layer combo to a QgsMapLayerCombobox

**Comment by pcav** [comment]
If I understand it correctly you want to keep it in case someone is using it for older projects. Isn't it better to at least add a "Deprecated" warning in the panel?

**Comment by Gustry** [comment]
It's already done @pcav 
And the panel is invisible by default for a few months already.

Just waiting to remove that code.

**Comment by pcav** [comment]
Strange, I still see it
![Schermata del 2020-04-24 11-37-47](https://user-images.githubusercontent.com/691842/80198166-f8881f00-861f-11ea-8074-b553215fd9f6.png)

**Comment by Gustry** [comment]
Hum indeed, we are not still talking about the same panel.
Thanks for checking.

This panel is hidden by default, it's only visible if you have at least one entry:
![Capture d’écran de 2020-04-24 11-43-04](https://user-images.githubusercontent.com/1609292/80198752-d6db6780-8620-11ea-8739-90710b8f0273.png)

I'm not sure about the one you are talking, which is indeed still visible (and I think it's still used). I will wait for some feedbacks first

**Comment by pcav** [comment]
OK, thanks.

**Comment by Gustry** [comment]
The code has been removed in LWC 3.7.0, I will remove the code when LWC 3.6 is not maintained anymore and we will agree on the plugin version
