### ISSUE TITLE
QGIS3 - Layer order issue

### ISSUE THREAD

**Issue by andrerjesus** [3liz/lizmap-plugin#123]
**What is the bug?**
Layer order are not being passed to Lizmap config file

Lizmap plugin 3 - doesn't work
Lizmap plugin 2 - works

**Steps to reproduce the issue**
Go to QGIS and add two layers and set:
Set layer order in QGIS3.
Set layer order in QGIS2.

Lizmap version: 3.1.14
QGis version: 3.2.3 / 2.18.24
Lizmap plugin version: 3.0.0 / 2.4.1
OS (windows, linux, macOS, android..): Windows 10
Browser (Firefox, Chrome...): Chrome
Lizmap data stored into Sqlite (default)? Postgresql

**Comment by Gustry** [comment]
Is this issue still valid ?

There are quite a few bugfix about layer order in latest version of QGIS server and LWC.
We are aware about a broken layer order, on the openlayers side either on FF or chromium IIRC.

**Comment by Gustry** [comment]
Closing for lack of feedback.

There were a lot of improvements on this side, with latest versions of QGIS.
