### ISSUE TITLE
lizmap should have a capital L for better readability

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-plugin#132]
![capture du 2019-02-11 10-22-29](https://user-images.githubusercontent.com/2145040/52554493-4f248700-2de7-11e9-903a-777b0553e514.png)

**Comment by Gustry** [comment]
I agree too, I could notice too.

I have fixed it. But I think QGIS is maybe a little bit confused by plugins.qgis.org providing `lizmap` and my git clone having now `Lizmap`. It should be correct after the plugin upload later. That's why I keep the ticket open to check later.

**Comment by Gustry** [comment]
Hum, the name is coming from the python package name. Plugins.qgis.org rejected first the new zip with `Lizmap`. I will update after that.

**Comment by nboisteault** [comment]
@Gustry thanks
