### ISSUE TITLE
problem dataviz

### ISSUE THREAD

**Issue by kino94** [3liz/lizmap-plugin#134]
Hi, we have a problem to create charts with dataviz.
In particular we have problem to create scatterplot, the other types of charts seem work except when we try to create one of them with more data (about 5000).

The result that show at the display is the following

![image](https://user-images.githubusercontent.com/48024513/53944135-0c409100-40bf-11e9-9b37-faaf6e691044.png)

The steps to reproduce the issue are the following:

Create the charts on the project in Qgis using Lizmap
- Save the project
- Refresh the page in Firefox
- Click on Dataviz icon

Configuration
- Lizmap version: Lizmap-web-client-release_3_2
- QGis version: 2.18
- OS: Ubuntu
- Browser: Firefox

**Comment by Gustry** [comment]
Maybe it's related to Lizmap Web Client instead of the Lizmap QGIS plugin?

**Comment by Gustry** [comment]
I'm closing for lacking of feedbacks. Feel free to reopen if necessary or a new ticket.
