### ISSUE TITLE
Improve the UI of the management of lists

### ISSUE THREAD

**Issue by laurentj** [3liz/lizmap-plugin#139]
In many list in the plugin, it is impossible to modify an item. We have to delete the item and to recreate it. 

This is a terrible UX. We should improve that :

when clicking on a line, the form at the bottom should be filled with the values of the item, and the button "add" should be renamed to "modify".

A better UX is to allow to edit directly the value into the cell. Probably it is more difficult to implement, though.

**Comment by mdouchin** [comment]
Totally agree. I would go for the first proposal, as it will be much easier indeed

**Comment by Gustry** [comment]
In QGIS, there are the green `+` and the red `-` to add/remove items in a list. I would be nice to use the same UX.

The green `+` and red `-` icons which are adding new rows:
![Sélection_012](https://user-images.githubusercontent.com/1609292/58274180-9d580780-7d92-11e9-9944-141ac7fe243e.png)

**Comment by Gustry** [comment]
Note to the developer who will do this ticket: 
```python
QIcon(QgsApplication.iconPath('mActionAdd.svg'))
```
to get the icon.

**Comment by Gustry** [comment]
This is now done for atlas panel. It will be soon for other panels.
