### ISSUE TITLE
nb locaux par parcelle

### ISSUE THREAD

**Issue by oznerol2** [3liz/lizmap-plugin#140]
Bonjour,

la continuité du projet est particulièrement intéressante avec la requette
majic_recuperation_locaux_par_parcelle.sql.

Néanmoins celle ci semble comptabiliser trop de locaux sur les parcelles a fort nombre de logements.

Avez vous plus de recul sur cette dernière?

Cdt,

**Comment by Gustry** [comment]
Bonjour,
Est-ce un ticket relatif au plugin QGIS lizmap?

**Comment by rldhont** [comment]
Probablement en lien avec https://github.com/3liz/QgisCadastrePlugin

**Comment by Gustry** [comment]
Ok, je ferme donc le ticket ici. Merci de créer un ticket sur le plugin cadastre.
