### ISSUE TITLE
Take account of the map canvas theme options defined in QGIS

### ISSUE THREAD

**Issue by arno974** [3liz/lizmap-plugin#150]
In QGIS it is possible to define specific [map canvas themes ](https://docs.qgis.org/testing/en/docs/user_manual/introduction/general_tools.html#configuring-map-themes)(from the layers panel). Defining a theme allows to automatically easily select different layers without having to do it manually. 

It might be interesting to have such option in Lizmap Plugin (and Lizmap Web). With this new tool we could pre-define some themes in QGIS and allow the user to switch from different themes in the web interface. This idea is similar to this [feature request](https://github.com/3liz/lizmap-plugin/issues/143) but it is probably a better alternative as it uses the native QGIS's functionalities.

This idea could be implemented in the web interface using a dropdown switcher (similar to map background for example).

**Comment by Gustry** [comment]
This feature has been covered in Lizmap Web Client 3.4.0 https://github.com/3liz/lizmap-web-client/releases/tag/3.4.0
