### ISSUE TITLE
Change order of layers in the edition tool and attribute table 

### ISSUE THREAD

**Issue by rmarzocchi84** [3liz/lizmap-plugin#151]
In the cfg text file there is the "order" key.   It would be possible to change it in the graphical interface of the plugin? 

In a project with a lot of layer I change the txt file manually, but I think it is not user friendly and error prone procedure

**Comment by mdouchin** [comment]
Il would be indeed very convenient for all the tables in Lizmap plugin : attribute tables, editing layers, filters, locate by layers, etc.

**Comment by rmarzocchi84** [comment]
Obviously yes ;-)

**Comment by Gustry** [comment]
Would it be better to have drag and drop of rows?

**Comment by rmarzocchi84** [comment]
Better but i do not know if it is possible with Qt

**Comment by Gustry** [comment]
Note for myself, for drag/drop, check what has been done in the case generator module.

**Comment by Gustry** [comment]
Some work in progress in my branch:
![Screenshot from 2019-11-23 11-51-48](https://user-images.githubusercontent.com/1609292/69477541-beec8700-0de7-11ea-9c29-17d91d64b7dc.png)

**Comment by Gustry** [comment]
This is now done for atlas panel. It will be soon for other panels.
