### ISSUE TITLE
Bug in Lizmap 3.1

### ISSUE THREAD

**Issue by news24lor** [3liz/lizmap-plugin#153]
## Description

in Layers section when I press Configure in popup sector I have this error:
Traceback (most recent call last):
              File ".../QGIS/QGIS3/profiles/default/python/plugins/lizmap/lizmap.py", line 1599, in configurePopup
              self.lizmapPopupDialog.groupBox.setStyleSheet(self.STYLESHEET)
             AttributeError: 'Lizmap' object has no attribute 'STYLESHEET'

## Context
* QGIS version: 3.8.3
* Lizmap version: 3.1
* OS: Mac OS, Windows 10

**Comment by Gustry** [comment]
Your affected version is 3.1.0.
You can update to 3.1.1.
Thanks
