### ISSUE TITLE
Layers from 'integrate layers or groups" from an existing QGIS project always available

### ISSUE THREAD

**Issue by arno974** [3liz/lizmap-plugin#156]
## Description
If layers are added from "integrate layers or groups" from an existing QGIS project the layers group name appears in the Lizmap Web interface event if the group has been removed from the current QGIS project and the LizMap layers tree extension.

QGIS (no "Fonds de carte" group): 
![image](https://user-images.githubusercontent.com/425243/66103216-1fb8c980-e5c6-11e9-8bde-014785467132.png)

Lizmap ("Fonds de carte" group) : :
![image](https://user-images.githubusercontent.com/425243/66103258-3d862e80-e5c6-11e9-9839-86f7a7d7af9c.png)

## How to reproduce

Had groups of layers from another QGIS project. 
Remove one of the group and generate Lizmap config file + save QGIS project
Open LizMap Web, the group name is still available (with no layers in it)

## Context
* QGIS version: 3.4
* Lizmap version: 3.1.1
* Lizmap Web : 3.3.0
* OS: Ubuntu

**Comment by nboisteault** [comment]
@arno974 Which Lizmap Web client version please ?

**Comment by arno974** [comment]
Yes sorry v. 3.3.0

**Comment by Gustry** [comment]
So reading the issue, the group has been removed from the lizmap layer tree in the QGIS plugin, right?
But it's still there on Lizmap Web client?

Can you check the content of the CFG file if it's correct or not?

**Comment by mdouchin** [comment]
Please also open the QGS file in a text editor, and search for "embed" word. Perhaps QGIS does not remove the layers in the layer tree, but only removes the `<maplayer>`

**Comment by arno974** [comment]
@Gustry Yes no group in the lizmap Layer tree (and in the cfg file) but the group appears in Lizmapweb .

@mdouchin In the QGIS file for embed projects groups are not specified only the name of the layers. The Layers from the group that has been deleted are not in the QGIS project file.

**Comment by Gustry** [comment]
So it seems clean from the QGIS desktop side (both CFG and QGIS project), right?
So I don't think this issue should stay open here. Can we move the ticket to LWC? Can you share the project?

**Comment by Gustry** [comment]
Gentle ping @arno974
