### ISSUE TITLE
"single tile" and "server cache" checkboxes no more mutually exclusive(?)

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-plugin#160]
Moreover now you can have both disabled.

This does not makes much sense to me, but of course if it is by design I would appreciate to understand the rationale.

This is on the latest version of the plugin.

**Comment by mdouchin** [comment]
it is indeed a regression, we should not be able to check them both at the same time.

**Comment by mdouchin** [comment]
it is indeed a regression, we should not be able to check them both at the same time.
