### ISSUE TITLE
"Configure" popup should be enabled only if "Lizmap" popup

### ISSUE THREAD

**Issue by Gustry** [3liz/lizmap-plugin#162]
![Screenshot from 2019-10-29 13-15-51](https://user-images.githubusercontent.com/1609292/67766295-6b885280-fa4e-11e9-980a-c3c50b9871f5.png)

@mdouchin @rldhont Do you confirm?

**Comment by rldhont** [comment]
I confirm

**Comment by pcav** [comment]
It would be good to remove it, it's misleading for new users.
Thanks.

**Comment by rldhont** [comment]
Popup configuration in QGIS is not supported for layer without geometry. So lizmap source is needed when user want to configure popup for non geographic vector layer.

**Comment by pcav** [comment]
What about disabling it for geometric layers?

**Comment by itsakifa** [comment]
@rldhont : Why is the popup configuration "qgis" not supported for layers without geometry? Is this a restriction from the QGIS side? 
My problem is that I would like to show children popups (without geometry) below the parents that have a "qgis"-configured popup using expressions and links. Is it possible to have different popup styles between parents and children?
I'm using QGIS 3.10 and Lizmap 3.3

**Comment by Gustry** [comment]
> Why is the popup configuration "qgis" not supported for layers without geometry?

It's new. It wasn't possible with QGIS 3.4 if I'm correct.
It's now possible to set a display expression in 3.10 indeed.

We just need to check it's working on the Lizmap side. Have you tried @itsakifa ?

**Comment by itsakifa** [comment]
@Gustry Yes I tried, it's not working on the Lizmap side, I can't select "qgis" as popup configuration.

**Comment by Gustry** [comment]
I mean we would need to check on the Lizmap Web Client side.

In the meantime if you want to try, you need to setup the QGIS Display expression on the tabular layer.
Manually edit the `cfg` file from Lizmap QGIS plugin and change for the given layer : 

```
"popupSource": "auto",
```

to

```
"popupSource": "qgis",
```

**Comment by itsakifa** [comment]
Ah, sorry! I tried but without success. I do not exclude that there is some configuration part missing in my project. I can barely make work the child popup for "auto" configuration and neither for "qgis" nor for "lizmap".

**Comment by Gustry** [comment]
Can you make a specific ticket for this one ?
This is a new behavior since QGIS 3.10, to be able to have maptip on tabular layer.
