### ISSUE TITLE
Lizmap should call the Project Server Validator from QGIS core

### ISSUE THREAD

**Issue by Gustry** [3liz/lizmap-plugin#167]
* [x] Make Project Server validator sipified (only in the GUI for now) in QGIS core
* Add some new checks in this validator:
  * [x] 1. Not possible to have two or many groups with the same name. Group must have different group names.
  * [x] 2. Layer and group starting or ending by a space
  * [x] 3. Project file name or project shortname cannot be used in layer name or group name
* [x] Lizmap should call this function from `qgis.core` when saving the CFG file

In the meantime, Lizmap should implement these checks in the plugin itself.

**Comment by Gustry** [comment]
@rldhont This can go in the QGIS Server check, no?

**Comment by rldhont** [comment]
@Gustry yes, it is.

**Comment by rldhont** [comment]
the project file name or project shortname cannot be used in layer name or group name

**Comment by nboisteault** [comment]
Group name starting or ending by a space too

**Comment by Gustry** [comment]
Ok, I have added your suggestions in the ticket.

**Comment by Gustry** [comment]
PR started https://github.com/3liz/QGIS/pull/1

**Comment by Gustry** [comment]
First part is done in QGIS 3.13 https://github.com/qgis/QGIS/pull/35900

@rldhont I tried but your code was already covering bullet point 1. No? Or a special scenario. Because you were reading all OWS names and check for duplicates within groups already.

For 2, I just checked, I couldn't replicate the issue. I tried a project in lizmap.
or maybe it's a blocker in some situations only ? When all sublayers are grouped together? @nboisteault 

I'm trying to be careful when adding these checks upstream in QGIS core because we shouldn't saying the the project is bad if it's working on the QGIS Server side.

**Comment by nboisteault** [comment]
@Gustry FYI, discussion we had about 2/ with @mdouchin in IRC the 30/01/2020.

```
1:15:44 - nboisteault : reluc: kimaidou: concernant les espaces en début et fin de nom pour les couches qui sont supprimés par qgis server mais pas par notre getconfig, qu'est ce qu'on fait ?
11:16:08 - nboisteault : on fait évoluer getProjectConfig ppur qu'il fasse un trim() ?
11:16:40 - kimaidou : nboisteault: on pourrait oui
11:17:12 - kimaidou : c'est mieux de blinder cela au niveau du code
11:18:31 - kimaidou : Le plugin lizmap pourrait prévenir sinon etrimaille lorsqu'il détecte un nom de couche avec des espaces de début ou fin ? NB: QGIS Server fait un trim des noms dans le GetCapabilities
11:18:59 - kimaidou : nboisteault: je crains aussi, car le config est le pivot, donc plutôt peut-être un check dans le plugin pour demander au user de prendre les bonnes résolutions
```

**Comment by Gustry** [comment]
Done in Lizmap plugin : 881057c336e136aeceec58318547973e6c452441

**Comment by Gustry** [comment]
Reopening, I want to make this warning more visible to users. 3.16 will be LTR soon

**Comment by Gustry** [comment]
In the `metadata` section, the plugin should write if the project was valid when the QGS project was saved.

**Comment by Gustry** [comment]
> In the metadata section, the plugin should write if the project was valid when the QGS project was saved.

Done

All these warnings should be centralized in a new panel, request #389
