### ISSUE TITLE
bottom-dock opened on load

### ISSUE THREAD

**Issue by brebe** [3liz/lizmap-plugin#172]
Good morning dear sirs,

how can i make the bottom dock (with attributes table) to be visibile and full size on load of the map ?
i searched but i couldnt find any specification about this.

Thank you in advance 

## Context
* QGIS version: 3.4
* Lizmap version:3.3.2
* OS: ubuntu 18.04

**Comment by nboisteault** [comment]
You have to use [documentation](https://docs.lizmap.com/current/fr/publish/advanced_lizmap_config.html#adding-your-own-javascript) to insert this script (not tested) : 

```javascript
lizMap.events.on({
        'uicreated': function(e) {	
             $('#button-attributeLayers').click();
             $('#bottom-dock-window-buttons .btn-bottomdock-size').click();
	}
});
```

**Comment by brebe** [comment]
thank you
