### ISSUE TITLE
Python error when saving multiatlas

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-plugin#173]
## Description
When saving a single layer in atlas in multiatlas branch I have this error :

Une erreur est survenue lors de l'éxécution du code Python: 

AttributeError: 'list' object has no attribute 'items' 
Traceback (most recent call last):
  File "/home/nboisteault/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Lizmap/lizmap.py", line 2917, in run
    self.get_config()
  File "/home/nboisteault/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Lizmap/lizmap.py", line 858, in get_config
    self.load_config_into_table_widget(key)
  File "/home/nboisteault/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Lizmap/lizmap.py", line 899, in load_config_into_table_widget
    if 'order' in list(json_config.items())[0][1]:
AttributeError: 'list' object has no attribute 'items'

Version de Python : 3.6.8 (default, Oct  7 2019, 12:59:55) [GCC 8.3.0] 
Version de QGIS : 3.4.13-Madeira Madeira, 64ad560274 

Chemin Python :
/usr/share/qgis/python
/home/nboisteault/.local/share/QGIS/QGIS3/profiles/default/python
/home/nboisteault/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/home/nboisteault/.local/lib/python3.6/site-packages
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/home/nboisteault/.local/share/QGIS/QGIS3/profiles/default/python
.
/home/nboisteault/3liz/infra/lizmap-qgis-3.4/lizmap-web-client/projets

## Context
* QGIS version: 3.4.13
* Lizmap version: master
* OS: Ubuntu 18.04

**Comment by Gustry** [comment]
Related to the work in the PR #170
