### ISSUE TITLE
atlasDuration should not be global in multiatlas

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-plugin#174]
## Description
`atlasDuration` parameter should be set by layer and not globally.
@rldhont @mdouchin Are you ok with that ?

**Comment by Gustry** [comment]
Let me know what I should do. I was indeed following the previous layout:
![Screenshot from 2019-11-19 12-44-05](https://user-images.githubusercontent.com/1609292/69143893-5db47300-0aca-11ea-99f8-8e154f85e2e0.png)

Layer options could be multi and global options unique. Should I change that?

**Comment by nboisteault** [comment]
`atlasDuration` was set for the whole atlas because there was only one layer. Now I think it is better to set this parameter for each layer separately.

**Comment by mdouchin** [comment]
I agree with @nboisteault

**Comment by Gustry** [comment]
Ok, in the new CFG version, I'm getting the duration in the layer config, see https://github.com/3liz/lizmap-plugin/pull/170#issuecomment-557154927

**Comment by Gustry** [comment]
Related to closed PR #170
