### ISSUE TITLE
atlasAutoPlay should be linked to a layer

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-plugin#175]
## Description
`atlasAutoPlay` parameter should be set by choosing between atlas layers. Or we could assume that the layer that should be autoplayed is the first in the table, in this case we need a way to move atlas layers.
@rldhont @mdouchin OK with that ?

**Comment by Gustry** [comment]
So `autoplay` is a global config. And if it's checked, then the first layer will be used in LWC?

I can add these blues arrows that QGIS has about moving rows up and down:
![Screenshot from 2019-11-19 12-39-54](https://user-images.githubusercontent.com/1609292/69143661-c6e7b680-0ac9-11ea-9676-d70d602827a6.png)

**Comment by nboisteault** [comment]
@Gustry OK for me ! Sorry I realize I should have put those issues in your PR and not in Lizmap plugin issues.

**Comment by Gustry** [comment]
![Screenshot from 2019-11-23 11-51-48](https://user-images.githubusercontent.com/1609292/69477541-beec8700-0de7-11ea-9c29-17d91d64b7dc.png)

I have added arrows to move layers down/up. So I will let you do the logic in LWC.
