### ISSUE TITLE
MultiAtlas : some fields are changing their value when going back on layer

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-plugin#177]
## Description
The first layer is configured correctly but when clicking back on it some fields switch to "boolean_field"  field in this case : 
![image](https://user-images.githubusercontent.com/2145040/69142662-8edf7400-0ac7-11ea-9c6d-23862edcae22.png)

**Comment by Gustry** [comment]
Thanks for the report. That's why I put the PR as `WIP` for now.
This is the main blocker I need to fix before I merge.

**Comment by Gustry** [comment]
Related to closed PR #170
