### ISSUE TITLE
Convert TCP PostGIS connection to UNIX socket

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-plugin#18]
When working on a database server, we normally use TCP/IP connections. Once the project is moved to the server, it should be faster using a local socket. It would be nice if the plugin would offer the option to automatically switch to local socket once deployed on the server. Tips should then be added to explain how to allow local connections on pg_hba.conf

**Comment by mdouchin** [comment]
What about using pg services to achieve this ? Would this be feasible ?

**Comment by pcav** [comment]
I think this would be a proper way to go. Thanks.

**Comment by Gustry** [comment]
@pcav Is this issue still relevant?

**Comment by pcav** [comment]
I think encouraging users to use services. e.g. in the documenttion, is the right way to go.
