### ISSUE TITLE
Link is lost when the dialog is open

### ISSUE THREAD

**Issue by Gustry** [3liz/lizmap-plugin#189]
## Description

* Setup a link on a layer.
* Save the CFG file. It's working in LWC.
* Open Lizmap plugin dialog again, the link is gone.

Similar to https://github.com/3liz/lizmap-plugin/issues/72

## Context
* QGIS version: 3.4.14
* Lizmap version: 3.2 HEAD
* OS: Ubuntu 19.10

**Comment by pcav** [comment]
Confirmed, quite annoying.

**Comment by Gustry** [comment]
Following a discussion with @rldhont : 

If the link is empty in the Lizmap config **and** the link `dataUrl` is not empty in the layer properties, so Lizmap will fill the `Link` section in the CFG with this value.

But when this value will be filled **one time from QGIS properties**, then we loose the information that this value wasn't set before and won't be synchronized anymore (because Lizmap will read it from the CFG and not from QGIS properties). @rldhont do we want to add a `source_link` with either `qgis` or `manual` ?
