### ISSUE TITLE
Mandatory fields in some configuration

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-plugin#194]
## Description
In the Form Filter, some fields are mandatory like field, min_date.

Other fields can be mandatory

## Context
* QGIS version: 3.4
* Lizmap version: 3.1.7
* OS: All

**Comment by Gustry** [comment]
List of compulsory fields per panel:

* Locate by layer : display field
* Attribute table : primary key
* Layer editing : *none*
* Tooltip layer : at least one
* Filter layer by user : login field
* Dataviz : Y field (X field is only compulsory according to the chart type)
* Time manager : start attribute
* Atlas : Primary key, Feature label, sort field
* Filter data with form : ALL fields except max date

**Comment by Gustry** [comment]
Mostly fixed. I could nearly close it. I will keep the ticket open for adding more form validation soon.

**Comment by Gustry** [comment]
This has been reviewed while porting all tabs to be editable. It should be fine now.
