### ISSUE TITLE
Duplicate menu items

### ISSUE THREAD

**Issue by timlinux** [3liz/lizmap-plugin#201]
## Description

Just installed Lizmap plugin and I get two entries in the web menu:

![image](https://user-images.githubusercontent.com/178003/73535454-7bcc1700-441b-11ea-9804-383479d0e367.png)

and 

![image](https://user-images.githubusercontent.com/178003/73535474-89819c80-441b-11ea-84b3-e815c0464b27.png)

## Context
* QGIS version: 3.11
* Lizmap version: 3.2.0
* OS: macOS

**Comment by Gustry** [comment]
Thanks @timlinux for the feedback. Fixed ;-)
