### ISSUE TITLE
Lizmap Plugin does not work by new QGis project extensie .qgz ??

### ISSUE THREAD

**Issue by NvBgm** [3liz/lizmap-plugin#209]
Lizmap Plugin does not work by new QGis project extensie .qgz ??

## Context
* QGIS version: 3.2
* Lizmap version: 3.4pre
* OS: Windows 10

The latest Lizmap plugin give a warning if i load a QGis project with the extensie .qgz
If i save the project in the older extensie qgs it works fine.
Is this a bug ?? 

![Knipsel](https://user-images.githubusercontent.com/8125819/73963306-5013ca00-4910-11ea-8cf9-997ce2fbb6bc.PNG)

**Comment by rldhont** [comment]
It is not a bug lizmap-web-client does not support`.qgz` file format.

You just have to save your project in `.qgs`

**Comment by NvBgm** [comment]
Oke thanks.
