### ISSUE TITLE
Label missing in published map

### ISSUE THREAD

**Issue by Naturtecnica** [3liz/lizmap-plugin#216]
## Description
Hi, got a problem with text labels. 
After setting labels of a point shpfile in Qgis, they are missing in Lizmap map.
I tried to change layer format, I tried to force labels but no goal.
Any suggest?

Thanx.

Lorenzo

## Context
* QGIS version: 3.4.15
* Lizmap version: 3.2.4
* OS: windows 10

**Comment by Gustry** [comment]
Duplicated in LWC : https://github.com/3liz/lizmap-web-client/issues/1513
