### ISSUE TITLE
BaseEditionDialog.py - Syntax error

### ISSUE THREAD

**Issue by Nekika** [3liz/lizmap-plugin#217]
## Description
Hello, 

I encountered a problem while trying to install the LizMap plugin on QGIS 3.4.

The error message revealed an error in BaseEditionDialog.py at line 23 :
```
self.config: BaseDefinitions
```
I tried to change this line by replacing the colon symbol by an equal symbol :
```
self.config = BaseDefinitions
```
I don't know if it's a real issue but after doing this the plugin started cleanly.

Hope it helps !

## Context
* QGIS version: 3.4 Madeira
* Lizmap version:  3.2.4
* OS: Debian 9

**Comment by Gustry** [comment]
No, it shouldn't be an `=`. Which Python version are you using? 
It's a Python annotation. I will fix it.

**Comment by Gustry** [comment]
Still curious about your Python version.

Please update to 3.2.5 which has been released.

**Comment by Nekika** [comment]
Thanks for your quick answer ! I'm sorry I didn't know about Python annotations...

My QGIS is currently using Python 3.5.2, should I upgrade it to 3.7/3.8 ?
