### ISSUE TITLE
Time manager: more time units to choose from

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-plugin#23]
It would be useful to be able to define the time interval in different measure unit (e.g. hours or days), as it will be painful for the users to calculate the conversions in case of more sparse data.

**Comment by Gustry** [comment]
This has been added I think : 

![Capture d’écran de 2020-02-05 09-47-32](https://user-images.githubusercontent.com/1609292/73825657-aa236b00-47fc-11ea-9b88-a167ac4934e5.png)

Can we close @pcav ?

**Comment by pcav** [comment]
Yes, thanks
