### ISSUE TITLE
Multiple popup report incorrect info

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-plugin#235]
When displaying popups for >1 element, when clicking on a tab for one element the second one is updated with the info from the first element.
See attached screenshots.
To reproduce it:
* click to show two popups
* click on the second tab of the first plugin (in the example, UBICAZIONE)
* click on the same tab for the second popup
Result: data from the first tab are displayed.
Expected: data from the second tab should be displayed.
Forms are generated using the `Copy from attribute form` function of the plugin.
Lizmap 3.3.4, QGIS 3.4 and 3.10.

**Comment by Gustry** [comment]
"In the HTML build by the plugin, the tab id has to include the feature id."

**Comment by Gustry** [comment]
Should be fixed with 31972b8caec5161827e68ed262977faf074c223e

**Comment by pcav** [comment]
Merci @Gustry !

**Comment by Gustry** [comment]
Why did you reopen? Is-it still a problem?
Did you regenerate the popup with the lizmap plugin version?

**Comment by pcav** [comment]
Sorry, I was too fast. I'm doing further chacks, I'll let you know soon, hopefully I'll close this again.
Sorry for the noise.

**Comment by pcav** [comment]
I confirm that this bug has been properly fixed, thanks.
The graphics of the popup, however, has changed, less readable IMHO: is this related to this fix? Or should I open another ticket?
Compare the example attached with the images above.
Thanks.
![Schermata del 2020-04-02 11-39-38](https://user-images.githubusercontent.com/691842/78234059-e579a780-74d6-11ea-9d3a-8b244724c701.png)

**Comment by Gustry** [comment]
Please open a new ticket, with before/after screenshots. This code has changed a lot in Lizmap recently.
