### ISSUE TITLE
Add trace for dataviz

### ISSUE THREAD

**Issue by Gustry** [3liz/lizmap-plugin#238]
Until now, we support Y and sometimes Y2. For Y, we can set a color or a field.

The CFG looks like (LWC 3.3):

```json
    "datavizLayers": {
        "0": {
            "title": "My graph",
            "type": "scatter",
            "x_field": "id",
            "aggregation": "",
            "y_field": "name",
            "color": "#00aaff",
            "colorfield": "",
            "has_y2_field": "True",
            "y2_field": "name",
            "color2": "#ffaa00",
            "colorfield2": "",
            "popup_display_child_plot": "False",
            "only_show_child": "True",
            "layerId": "lines_7ddd81b1_8307_4aa2_8b7a_a0b7983f33e3",
            "order": 0
        }
    },
```

For scatter, bar, polar, histogram, we should support multiple traces (Y, Y2, Y3,....)

```json
    "datavizLayers": {
        "0": {
            "title": "My graph",
            "type": "scatter",
            "x_field": "id",
            "aggregation": "",
            "traces":[
                {
                    "y_field": "name",
                    "color": "#00aaff",
                    "colorfield": "",
                },{
                    "y_field": "name",
                    "color": "#00aaff",
                    "colorfield": "",
                },
            ],
            "popup_display_child_plot": "False",
            "only_show_child": "True",
            "layerId": "lines_7ddd81b1_8307_4aa2_8b7a_a0b7983f33e3",
            "order": 0
        }
    },
```

For other kind of charts, we should keep what it's already implemented. There are already rules about allowing or not Y2 fields.

Of course, this **mustn't** break any LWC servers (even for people doing QGIS plugin upgrade without doing it on the server side).

@mdouchin Any thought? Is-it alright?

**Comment by mdouchin** [comment]
Good for me. Do not forget the `z_field` for lizmap-plugin dev branch, so that sunburst and future html and scatter3d can be supported as well

**Comment by Gustry** [comment]
Just in case I want to rework my HTML JSON formatter later, I keep the diff here. I got some issues with the size of the widget.

[html.diff.txt](https://github.com/3liz/lizmap-plugin/files/4388231/html.diff.txt)
