### ISSUE TITLE
Popup generated from form became less readable

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-plugin#253]
Please compare the previous popup:
![](https://user-images.githubusercontent.com/691842/75149046-5c19cd00-5701-11ea-81f7-9acfcc92d6bd.png)
with the current one, generated with 3.2.11, attached.
![Schermata del 2020-04-02 11-39-38](https://user-images.githubusercontent.com/691842/78236116-dfd19100-74d9-11ea-841d-a8630a5b5ee0.png)
IMHO previous version was much more clear.

**Comment by Gustry** [comment]
Fixed 2f13443724920413dc9bbce3bb63b140c9cadd45

**Comment by pcav** [comment]
Gee, that was fast! Thanks @Gustry , looking forward for the new version.
