### ISSUE TITLE
Dataviz - Add option to chosse theme between dark and light

### ISSUE THREAD

**Issue by mdouchin** [3liz/lizmap-plugin#256]
Lizmap 3.4 will allow to let the user choose between two themes for the Dataviz main panel. We need a new configuration item in the plugin, under Dataviz tab

* property `datavizTheme` wich will be stored in the `options` property of the exported JSON cfg file
* values : `dark` or `light` displayed as `Dark` and `Light`
* Title : `Dataviz panel theme`
* Tooltip: `Choose between dark and light theme for the dataviz panel`

**Comment by Gustry** [comment]
Done 82702dd
