### ISSUE TITLE
Bad display of 'Copy the form drag &amp; drop template'

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-plugin#281]
## Description
https://github.com/3liz/lizmap-plugin/blob/b15f53e655571ab6d3b19074b68e1fe5123b2e5f/lizmap/resources/ui/ui_lizmap.ui#L1194
![image](https://user-images.githubusercontent.com/2145040/88898467-1089c300-d24d-11ea-9dae-3c853022eb92.png)

Maybe write 'and' and not '&amp;' as in 'Drag and drop designer' in QGIS Attributes form tab.

**Comment by nboisteault** [comment]
Also should it not be 'Copy the drag and drop form template'?

**Comment by Gustry** [comment]
![Screenshot from 2020-07-30 10-29-39](https://user-images.githubusercontent.com/1609292/88900439-aa526f80-d24f-11ea-827a-7d8c6b9ad2a8.png)

Yes, we should follow QGIS label.

**Comment by Gustry** [comment]
Fixed according to the vote : f67e213a9c2a9ed0132ba6fcfd6cfe51dd247e6c
