### ISSUE TITLE
Alert for ATLAS where for layer selected is not enabled WFS

### ISSUE THREAD

**Issue by rmarzocchi84** [3liz/lizmap-plugin#288]
I suggest to add an alert for ATLAS where for layer selected is not enabled WFS. It is the same behaviour of the plugin for "editing" and "localize by layer" functions

**Comment by rmarzocchi84** [comment]
![image](https://user-images.githubusercontent.com/4061154/92571854-f0094b80-f283-11ea-804e-60245ae89156.png)

**Comment by Gustry** [comment]
I have considered this as a bug, people would have issues on the LWC side.
Done in 92c6858afbb854c015bcd262c2c0a7e179cf514f

**Comment by rmarzocchi84** [comment]
well done @Gustry many thanks!
