### ISSUE TITLE
Dev: isinstance expected 2 arguments

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-plugin#295]
https://github.com/3liz/lizmap-plugin/blob/ce5553f18e55beb417db2fcce7e3d8cf202aea65/lizmap/plugin.py#L1459
This line is
```py
if isinstance(val['default']):
```
and could be
```py
if isinstance(val['default'], (list, tuple)):
```

**Comment by Gustry** [comment]
Damned, this kind of error should have been raised by a error somewhere :(

Fixed in 1c05e4c
Depoyed on packages.3liz.org
