### ISSUE TITLE
Default base layer and base layers order

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-plugin#30]
The user should be able to choose the default base layer and in which order they are displayed in Lizmap web client (less important).

**Comment by stuggi05** [comment]
That would be very nice.

btw Is it possible to define the deafult base layer in an easy way in the .js-file?

**Comment by nboisteault** [comment]
Here is what I changed in lizmap/www/js/map.js : 

ORIGINAL : 
`    // get the baselayer select content
    // and adding baselayers to the map
    //var select = '<select class="baselayers">';
    var select = [];
    baselayers.reverse();
    for (var i=0,len=baselayers.length; i<len; i++) {
      var baselayer = baselayers[i]
      baselayer.units = projection.proj.units;
      map.addLayer(baselayer);
      var blConfig = config.layers[baselayer.name];
      if (blConfig)
        select += '<option value="'+blConfig.name+'">'+blConfig.title+'</option>';
      else
        select += '<option value="'+baselayer.name+'">'+baselayer.name+'</option>';
      /*
      if (blConfig)
        select.push('<input type="radio" name="baselayers" value="'+blConfig.name+'"><span class="baselayer-radio-label">'+blConfig.title+'</span></input>');
      else
        select.push('<input type="radio" name="baselayers" value="'+baselayer.name+'"><span class="baselayer-radio-label">'+baselayer.name+'</span></input>');
        */
    }
`

MODIFIED : 
`    // get the baselayer select content
    // and adding baselayers to the map
    //var select = '<select class="baselayers">';
    var select = [];
    baselayers.reverse();
    for (var i=0,len=baselayers.length; i<len; i++) {
      var baselayer = baselayers[i]
      baselayer.units = projection.proj.units;
      map.addLayer(baselayer);

      // NBT : hack pour afficher un fond de carte en particulier en attendant https://github.com/3liz/lizmap-plugin/issues/30
      var selected = '';

      if(capabilities.service.title=='TITLE OF YOUR PROJECT HERE' && baselayer.name=='NAME OF YOUR BASEMAP HERE'){
        selected = 'selected';
        map.setBaseLayer(map.getLayersByName(baselayer.name)[0]);
      }

      var blConfig = config.layers[baselayer.name];
      if (blConfig)
        select += '<option value="'+blConfig.name+'" '+selected+'>'+blConfig.title+'</option>';
      else
        select += '<option value="'+baselayer.name+'" '+selected+'>'+baselayer.name+'</option>';
      /*
      if (blConfig)
        select.push('<input type="radio" name="baselayers" value="'+blConfig.name+'"><span class="baselayer-radio-label">'+blConfig.title+'</span></input>');
      else
        select.push('<input type="radio" name="baselayers" value="'+baselayer.name+'"><span class="baselayer-radio-label">'+baselayer.name+'</span></input>');
        */
    }`

Basemap names are : Google Streets, osm, ignphoto for example.

**Comment by stuggi05** [comment]
THX!!

**Comment by nboisteault** [comment]
Though with that script I noticed that if you use a permalink with a different base layer than default you'll get the default base layer selected in combobox. I might take some time to fix this.

**Comment by josemvm** [comment]
Thanks!

it would be best to select through the plugin...

**Comment by nboisteault** [comment]
Of course it would be best but it has to be developed.
@rldhont : what would cost the development of this feature? Maybe we can fund it with all interested people?

**Comment by josemvm** [comment]
yes it's true and of course you're right. so, It's a suggestion for the future!

**Comment by rldhont** [comment]
Fix in commit 15982a84873719e28aafb36bb96d32043d302206 [FEATURE] Baselayers - Choose active baselayer at map startup

**Comment by pcav** [comment]
Thanks. Any plans to backport it to 2.x?

**Comment by rldhont** [comment]
Done commit c875b1d2cf063a56769ab6e88878b8fa19cb14e8
