### ISSUE TITLE
Variable "décompte" at launch

### ISSUE THREAD

**Issue by christophe-mm** [3liz/lizmap-plugin#301]
hi !

when the plugin is launched, a .back is created.
I have a message in the log:
CRITICAL    Error with list value="décompte"
CRITICAL    Error while reading the CFG file
then impossible to recreate a .cfg

what is this variable "décompte" ?
qgis 3.16 | lizmap 3.4.0-alpha.3 | plugin 3.2.18 

Thank you all
Christophe

**Comment by christophe-mm** [comment]
delete and recreat

**Comment by Gustry** [comment]
Ok, it seems you could fix your issue.
But it seems you got a real Python error. A layer or a setting in Lizmap called "Décompte" ?

> lizmap 3.4.0-alpha.3 | plugin 3.2.18

Side note, you need to use 3.2.19-beta from the `dev` branch if you want to try Lizmap 3.4 features.
Either use git or https://packages.3liz.org

**Comment by christophe-mm** [comment]
nowhere is mention "Décompte" in my project.
thanks for the package

**Comment by christophe-mm** [comment]
Error with list value="décompte"
error came from a dataviz slag 
on cfg : datavizLayers
"aggregation": "d\u00e9compte",

**Comment by Gustry** [comment]
Can copy/paste your `datavizLayers` section ?
Which Lizmap plugin version ?
With the current `dev` version ?

**Comment by christophe-mm** [comment]
"3": {
            "title": "mlkjhgf",
            "type": "histogram",
            "x_field": "qzerty",
            **"aggregation": "d\u00e9compte",**
            "y_field": "qsdfghj",
            "color": "#e31a1c",
            "colorfield": "",
            "has_y2_field": "False",
            "y2_field": "",
            "color2": "",
            "colorfield2": "",
            "popup_display_child_plot": "False",
            "only_show_child": "False",
            "layerId": "azertyuio",
            "order": 3
        },

**Comment by Gustry** [comment]
It should be fixed with the next Lizmap release.
