### ISSUE TITLE
WYSIWYG editor and HTML popup templates

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-plugin#31]
It would be nice for non-developer people to have a wysiwyg editor to create the HTML popup templates and CSS styles.
Ideally there would be a dropdown list filled with layer's attributes to select them and have the {$attribute} variable put in the editor.

**Comment by Gustry** [comment]
Done since version 3.11.0 - 2023-03-09

* Add a new HTML wizard for the
  * QGIS HTML Maptip popup
  * HTML template in the dataviz
  * HTML layout in the dataviz
  * plot description in the dataviz
