### ISSUE TITLE
Update problem and save LWC version

### ISSUE THREAD

**Issue by rmarzocchi84** [3liz/lizmap-plugin#311]
## Description
When I update the plugin I have a lot of entries in the web menu of QGIS:
![image](https://user-images.githubusercontent.com/4061154/100475741-29639180-30e4-11eb-9991-2bc1fa0ca6fa.png)

When I choose the version of LWC the information is saved in the cfg file, but the plugin do not read this information
![lizmap_problem](https://user-images.githubusercontent.com/4061154/100475851-6c256980-30e4-11eb-831c-dc03d16aa73a.gif)

## Context
* QGIS version: 3.10.12
* Lizmap version: 3.3.0  (plugin) LWC 3.3.11
* OS: Windows 10 pro

**Comment by Gustry** [comment]
> When I update the plugin I have a lot of entries in the web menu of QGIS:

You would need to describe what you are doing. I'm not able to replicate. I only have a single item.

> When I choose the version of LWC the information is saved in the cfg file, but the plugin do not read this information

Fixed in 589511843eff84238c013ef8363c1192e6f74a0e

Please keep a ticket per issue.
