### ISSUE TITLE
"Max feature in popup" limited to 199

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-plugin#316]
## Description

![image](https://user-images.githubusercontent.com/2145040/101380216-836b1080-38b5-11eb-9a32-099427779d8b.png)

@Gustry could this limitation be increased or there are some technical reason to keep it?

Support ticket #897

## Context
* QGIS version: all
* Lizmap plugin version: 3.3.1
* OS: all

**Comment by Gustry** [comment]
Done in 2682acb

**Comment by Gustry** [comment]
I'm not part of the project anymore. I have no idea, please raise a new ticket if needed.
