### ISSUE TITLE
"Toggle" has to be available for "Group as layer"

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-plugin#322]
## Description

The "Toggle" option has been disabled for layers group but has to be available when "Group as layer " is checked.

## Context
* QGIS version: all
* Lizmap version: 3.3.1
* OS: all

**Comment by rmarzocchi84** [comment]
I confirm the same problem 

![image](https://user-images.githubusercontent.com/4061154/101789602-c9b4af80-3b01-11eb-9322-13998a8ed22c.png)
