### ISSUE TITLE
Layer from postgresql

### ISSUE THREAD

**Issue by RenataB** [3liz/lizmap-plugin#33]
Hi, I'm doing an experiment about using lizmap to publish some layers coming from a postgresql+postgis server.
So, I installed on the same PC (Debian) Postgresql, postgis, Qgisserver, php (with postgresql extension), phyton and so on and I created a very simple project with 3 layers coming from DB.
Then I created repository on lizmap, doing everything I thought was correct but... I can't see my DB layers with lizmap project.
Is there something I can check (or not) in the lizmap plugin? Something to check on the DB?
Thank you very much!
Renata.

**Comment by ronixp** [comment]
Tengo el mismo problema. Realice la instalación con vangrant, y no puedo visualizar la capa de origen de BD postgis.
Según tu recomendación, al parecer el servidor esta devolviendo datos (herramientas de desarrollo), sin embargo no los muestra en la web.
