### ISSUE TITLE
Toggle checkbox when label 'Display related...' is checked

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-plugin#330]
## Description

When this label is checked the checkbox should be toggled.

![image](https://user-images.githubusercontent.com/2145040/104616770-fe7ccf00-568a-11eb-8998-8641b863796b.png)

## Context
* QGIS version: 3.10
* Lizmap version: 3.4.0
* OS: Ubuntu 18.04

**Comment by Gustry** [comment]
The reason why it's not done it's because this is a long label.
QLabel has a wordwrap option, while QCheckbox doesn't have wordwrap option.
