### ISSUE TITLE
time manager - lost the label parameter

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-plugin#336]
hi @Gustry 

i have noticed that the plugin has no longer the `label `parameter for the time manager tool...

thanks

Lizmap version: 3.4.2
Lizmap plugin: 3.4.3
QGIS Server FULL version: 3.10.14
QGIS Desktop FULL version: 3.10.14

**Comment by Gustry** [comment]
It's not "lost", but it has been removed for the release 3.4

@mdouchin Not used anymore in LWC 3.4 ?

**Comment by rldhont** [comment]
The label parameter is no longer required. The time manager in Lizmap-Web Client 3.4 uses WMS Filter instead of vector displaying.

**Comment by Gustry** [comment]
I think we can close this ticket.
