### ISSUE TITLE
Edition Tool setting shows Python error

### ISSUE THREAD

**Issue by Nokram** [3liz/lizmap-plugin#339]
### What is the bug?
J'ai un problème avec le plugin Lizmap lors de la configuration du projet au niveau de l'édition de couche. 
Une erreur Python apparait. 
Il me semblait pourtant qu'on pouvait éditer la donner avant la 3.4 de Lizmap. 
**Note : Je ne peux ajouter aucune couche**
**Note 2 : Même avec un projet neuf, je ne peux rien faire**

I have a problem with the Lizmap plugin when configuring the project at the layer editing level. 
A Python error appears. 
It seemed to me that you could edit the layer before the 3.4 version of Lizmap.
**Note: I can't add any layers.**
**Note 2: Even with a new project, I can't do anything**.

### Steps to reproduce the issue

Simplement cliquer sur le bouton Edition de couche fait apparaitre le bug.

Simply clicking on the Edit Layer button brings up the bug. 

### Expected behavior
J'aimerais tout simplement pouvoir activer l'édition de table attributaire

I would just like to be able to activate the attribute table edition

### Screenshots and logs
```
2021-03-31T14:30:54     WARNING    Traceback (most recent call last):
              File "C:/Users/Aorus/AppData/Roaming/QGIS/QGIS3\profiles\Alexis 3.4.13-3/python/plugins\lizmap\forms\edition_edition.py", line 70, in layer_changed
              self.provider.setText(layer_provider(layer))
              File "C:/Users/Aorus/AppData/Roaming/QGIS/QGIS3\profiles\Alexis 3.4.13-3/python/plugins\lizmap\definitions\edition.py", line 14, in layer_provider
              return layer.dataProvider().name()
             AttributeError: 'NoneType' object has no attribute 'dataProvider'
```
             

### Environment

 - Lizmap version: 3.3.14
 - QGIS Server FULL version: 3.4.13
 - QGIS Desktop FULL version: 3.4.13
 - OS (Windows, Linux, MacOS, Android…): QGIS Desktop (W10) QGIS Server (Debian10)
 - Browser (Firefox, Chrome…): Chrome / Edge / Brave
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL?

**Comment by Nokram** [comment]
### **UPDATE** - **SOLVED**
Cette erreur apparait quand on utilise un mauvais format de fichier. 
Je ne savais pas qu'il fallait impérativement passer par **sqlite** ou **postgresql**. 

Il n'y a pas de message de prévention ou d'erreur pour indique que l'on utilise pas les bons formats de fichiers dans le projet QGIS. 

Il faut améliorer cette partie là de l'extension Lizmap avec un message de prévention en en-tête et un message d'alerte rouge si on "force" la manipulation dans la mauvaise voie.

_____

This error appears when you use the wrong file format. 
I did not know that it was necessary to use **sqlite** or **postgresql**. 

There is no warning or error message to indicate that the wrong file formats are used in the QGIS project. 

This part of the Lizmap plugin needs to be improved with a prevention message in the header and a red alert message if you "force" the manipulation in the wrong way.

**Comment by Gustry** [comment]
> Il faut améliorer cette partie là de l'extension Lizmap avec un message de prévention en en-tête et un message d'alerte rouge si on "force" la manipulation dans la mauvaise voie.

The plugin will already hide all non compatible layers. It's only showing sqlite base layer or postgresql.
If you have 1 shapefile and a postgresql layer, the combobox will only show the PG layer.

You got the error, because you didn't get **any** compatible layer in your project.

**Comment by Gustry** [comment]
Now, on each edition panel, there is a help button to the specific feature : d7754beb233d9d5eeedf234dc7d37394123100b1

**Comment by Nokram** [comment]
> > Il faut améliorer cette partie là de l'extension Lizmap avec un message de prévention en en-tête et un message d'alerte rouge si on "force" la manipulation dans la mauvaise voie.
> 
> The plugin will already hide all non compatible layers. It's only showing sqlite base layer or postgresql.
> If you have 1 shapefile and a postgresql layer, the combobox will only show the PG layer.
> 
> You got the error, because you didn't get **any** compatible layer in your project.

I mainly work with gpkg, so yes, the plugin hides these layers. 
However, have a python error without comment when I click on + button, instead of a top message like in attribute table panel (which it's mentionned to have wfs enabled) will be welcome. 
A message on the top like "You have to use only spatialite or postgresql layers" will be most user-friendly than a python error, even a helpbox exists.

**Comment by Gustry** [comment]
Sorry we misunderstood :)

Of course, the python error is not what we wanted. It was a side effect.
I was somehow explaining what was triggering the Python error, for me to fix it.

Please report any Python error you can have :)
