### ISSUE TITLE
Filtering data on user groups

### ISSUE THREAD

**Issue by RenataB** [3liz/lizmap-plugin#34]
Hi Michael, 
just seen your tutorial here http://vimeo.com/83966790 regarding filtering data in a layer and I tried to make the same with my data. I've got a layer containing municipalities with a field named "gruppo" that could be "VI", "PD", "VR", and so on, the abbreviations for the 7 cities of my region.
Then I created 7 groups having id like the 7 cities, 7 users one for every group, set the project to be seen from the 7 groups, put in the LizMap plugin the information about the field used as filter, uncheck the client cache for the layer having the filter, deleted server and browser caches but... nothing happens: my users always see every records of the table. It's very strange that admin see everything too and it isn't in any of the groups that could use the project.
Is there something to check?
Thank you!

**Comment by Gustry** [comment]
It seems it's a Lizmap Web client issue. There is already this ticket https://github.com/3liz/lizmap-web-client/issues/988 please use it.
