### ISSUE TITLE
An error ja_JP in the Japanese environment.

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [3liz/lizmap-plugin#349]
## Description
User interface traslation :日本語   NG
User interface traslation :American English    OK

Error:
"C:/Users/ryu/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lizmap\__init__.py", line 56, in classFactory
              return Lizmap(iface)
              File "C:/Users/ryu/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lizmap\plugin.py", line 510, in __init__
              self.dlg.qgis_and_lwc_versions_issue.setText(text.format(version=current))
             KeyError: 'バージョン'

## Context
* QGIS version:3.16.8. 
* Lizmap version:3.5.3
* OS: windows10

**Comment by Gustry** [comment]
Hi @yamamoto-ryuzo 

This error is coming the japanese translation and not from the Lizmap plugin.

I went to check on Transifex : 

![Screenshot from 2021-07-08 17-00-28](https://user-images.githubusercontent.com/1609292/124945023-17e54f00-e00e-11eb-9fe3-34ed55ff4b78.png)

When you see `{foo}`, never translate the `foo`. It's like a token.

* Version {version} not maintained anymore

must have been translated

* バージョン {version} は管理されていません‎


You should also fix other strings : "There is some known issues using this version of Lizmap Web Client and this QGIS Desktop and QGIS Server {version}. Check the version compatibility." 

which have been translated : 

Lizmapウェブクライアントのこのバージョンを使用して、いくつかの既知の問題があり、このQGISデスクトップとQGISサーバー{バージョン}。‎‎を確認してください。‎‎バージョンの互換性。‎

Do not translate {}


Let me know when you have finished.

**Comment by yamamoto-ryuzo** [comment]
Hi!Gustry 

I understood that {} would not be translated.
Returned {} in transifex not to be translated.
It was a very good study.
Thank you very much.

![image](https://user-images.githubusercontent.com/86514652/124991584-d475f980-e07c-11eb-8112-2badf948ae31.png)

**Comment by Gustry** [comment]
Ok, I will release a new version soon with your translation.

Thanks for your contribution to Lizmap.
https://www.transifex.com/3liz-1/lizmap-documentation/language/ja/ I think you should focus for files having "master" in their names (related to the next version of Lizmap)

Lizmap is using Jelix as a framework, so there is also strings in https://www.transifex.com/3liz-1/jelix/dashboard/

Let me know if you have any questions.

**Comment by yamamoto-ryuzo** [comment]
Hi!Gustry
7/14
We have confirmed the restoration of operation in the Japanese environment.
Thank you very much.

**Comment by Gustry** [comment]
Thanks for the feedback
