### ISSUE TITLE
Dataviz=null , TimeManager=Dataviz , Atlas=TimeManager , Log=Atlas

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [3liz/lizmap-plugin#366]
## Description
![image](https://user-images.githubusercontent.com/86514652/134499828-4b1715ce-a328-45fc-ae0d-58dc7ffc8e59.png)
 etc

## Context

lizmap-plugin 3.6.0

**Comment by Gustry** [comment]
It has been fixed.
