### ISSUE TITLE
Where is it　"You haven't provided any Lizmap URL in the first Information panel."

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [3liz/lizmap-plugin#367]
## Description
![image](https://user-images.githubusercontent.com/86514652/134519214-a07cc778-15fb-4ddc-bb0a-4fc13c1a4468.png)

## Context
* QGIS version: 3.16
* Lizmap version:3.4.6
* OS: windows10

**Comment by Gustry** [comment]
Sorry, my bad.
Fixed in 3.6.2 (available in 5 minutes on plugins.qgis.org)
