### ISSUE TITLE
Not completing to lad the map

### ISSUE THREAD

**Issue by kirui-max** [3liz/lizmap-plugin#369]
## Context
* QGIS version: 3.16
* Lizmap version: 3.3.4
* OS: Windows 10

**Comment by Gustry** [comment]
Hi,

For question/issue, about Lizmap web client, please raise your issue in Lizmap Web Client repository https://github.com/3liz/lizmap-web-client

But for your issue, it's seems : 
* either QGIS Server is not installed, or the URL correctly configured
* some layers are invalid in your project ? Maybe postgresql credentials ? https://github.com/3liz/lizmap-web-client/issues/1638

Related to :
```
QGIS version: 3.16
Lizmap version: 3.3.4
```

![Screenshot from 2021-09-27 08-59-16](https://user-images.githubusercontent.com/1609292/134859589-678d84fd-aece-4c60-aaec-8d5e706c0169.png)

There is a warning in Lizmap plugin ,first panel about some incompabilities with QGIS 3.16 and Lizmap Web Client : 3.3.

And also, 3.3.4 is very old, as you can see, it's 3.3.16

So you should first check Lizmap Web Client version, QGIS Version and PostGIS database credentials mentioned in the ticket above. You can open a new ticket if necessary.
