### ISSUE TITLE
print scale; svg

### ISSUE THREAD

**Issue by umbiz** [3liz/lizmap-plugin#37]
Hi

I found this in lizmap:
the printing scale, based on the presence or not of public base layer, is incorrect
![3](https://cloud.githubusercontent.com/assets/9987595/5486430/b108a600-86a6-11e4-9395-0d3021c4d6f0.jpg)

![1](https://cloud.githubusercontent.com/assets/9987595/5486425/a3ff779a-86a6-11e4-8a5b-9c1cf83bc1e1.jpg)
;

time manager (that's cool !!!!): if i use standard symbols svg, it's ok with Qgis but does not appear on the web.

thanks

**Comment by Gustry** [comment]
This looks like a QGIS Server issue. Can you try again with QGIS 3?

Did you QGIS Layout/Composer work? (the scale was updated in a PDf export for instance)

**Comment by umbiz** [comment]
Hi, now i'm using qgis and qgiserver 3.4.10 and is all ok
thanks
