### ISSUE TITLE
How to publish PostgreSQL + PostGIS project

### ISSUE THREAD

**Issue by kirui-max** [3liz/lizmap-plugin#370]
## Description

I am workin on windows 10 and looking to publish my QGIS map/project using lizmap web client from PostgreSQL + PostGIS. I have looked at the documentation and didn't find help.  I have managed to publish my test project from shp but the repository could not finish loading when i tried to view it on google chrome and firefox. Although I have raised it as an issue separately from this. My intention is to publish a project from the below description.

## Context
* QGIS version:  3.10-3.16
* PostgreSQL Ver: 9.5 – 11.x
* PostGIS Ver: 2.x
* Lizmap version: 3.3.4
* OS: Debian 10

**Comment by Gustry** [comment]
Hi,

I have already answered you in #369 

Related to your version : 

![Screenshot from 2021-09-27 08-59-16](https://user-images.githubusercontent.com/1609292/134859589-678d84fd-aece-4c60-aaec-8d5e706c0169.png)

So upgrade to latest Lizmap bugfix release.

For posgtresql issue, you should check credentials in the QGS project : https://github.com/3liz/lizmap-web-client/issues/1638
