### ISSUE TITLE
Lizmap Error: "You need to open a QGIS project, using the QGS extension, before using Lizmap."

### ISSUE THREAD

**Issue by Alex-Cuco** [3liz/lizmap-plugin#386]
## QGIS Lizmap widget error on start

Hi! I have been trying to create an web server using the Lizmap plugin on QGIS. I am a newbie with Lizmap, and I do not know what I am doing wrong... A pop-up window shows up after I click on the widget saying: "You need to open a QGIS project, using the QGS extension, before using Lizmap." I have an open QGIS project, and I even followed this tutorial: https://opengislab.com/blog/2018/7/19/using-lizmap-plugin-to-publish-web-maps

Could you help me with this issue? Thanks!

## Context
* QGIS version: 3.16.13
* Lizmap version: 3.6.4
* OS: Windows 10

![image](https://user-images.githubusercontent.com/91185914/144195385-142c2b5f-9cd7-4dd3-b797-52e59587d2ae.png)

**Comment by Gustry** [comment]
You need to use the QGS extension.
If you have this error, either you have not opened a project, or your extension is not QGS but QGZ.
Change the format when saving your project.
I will rephrase.

**Comment by Alex-Cuco** [comment]
Hi Gustry! That was it! I just started using QGIS and I did not understand the error message... Thanks a lot! :)
