### ISSUE TITLE
"fixed_scale_overview_map": true

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-plugin#413]
true is default value for this new parameter

if the user uncheck this option in the plugin, this parameter doesn't appears in the cfg file, so the true value is assumed by default

ps: the value for this parameter, unlike everyone else, it is not described with capital letter (True) and not between quotes ("True")

**Comment by Gustry** [comment]
Thanks for checking. I will fix.

> ps: the value for this parameter, unlike everyone else, it is not described with capital letter (True) and not between quotes ("True")

Yes, it's expected. It was legacy to use strings for boolean value.
