### ISSUE TITLE
Plugins installed in Qgis server are not visible in Lizmap  

### ISSUE THREAD

**Issue by juwizeye** [3liz/lizmap-plugin#421]
## Description
Hello,  I have been using lizmap for few months now and I want to improve it by adding some plugins. I am using qgis-plugin manger to install wfsOutputExtension and atlasprint plugins. I don't have  errors while installing them in Qgis server but they are not visible in lizmap. 
![image](https://user-images.githubusercontent.com/96420889/170245504-be9570dd-16f1-4a74-983c-0d9ae0a64220.png)

## Context
* QGIS version: 3.16
* Lizmap version: 3.5.1 
* OS: Lunix
I don't understand why it doesn't work . is it because I installed it with user root while  i am using user www-data for lizmap? 
are they special configuration (apart from setting the plugin) path that i must add to Qgis server or Lizmap ?

**Comment by Gustry** [comment]
Your question is only linked to QGIS Server, not Lizmap.
You should check your QGIS Server configuration : https://docs.qgis.org/3.22/en/docs/server_manual/plugins.html 
* user running QGIS server
* file rights
* folder where you are installing plugins

**Comment by juwizeye** [comment]
thank you for response @Gustry, I am using ngnix instead of apache. do you know to set qgis server configurations on Nginx(for exemple giving HTTP authorizations ) or where I can find documentations on that? it will be very useful for me.

**Comment by Gustry** [comment]
You need to check QGIS Server and Nginx documentation : https://docs.qgis.org/3.22/en/docs/server_manual/getting_started.html#nginx-configuration
