### ISSUE TITLE
Disable legend image is not working on 3.8.0 version

### ISSUE THREAD

**Issue by ygorigor** [3liz/lizmap-plugin#425]
## Description

Select `Disable the lengend image` for some layers.
Press `Apply` close and reopen Lizmap plugin window.
All options are switched back to `Hide legend image at startup`

* QGIS version: 3.22.7 (LTR)
* Lizmap version: 3.5.3
* OS: Ubuntu

**Comment by Gustry** [comment]
Confirmed, I will fix this ASAP today and release a new version.
