### ISSUE TITLE
The popup source is changed from QGIS to AUTO by itself.

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [3liz/lizmap-plugin#428]
## Description
When I select QGIS in the POPUP settings, exit, and then reload, it is set to Auto on its own.

## Context
* QGIS version: 3.224
* Lizmap version:3.5.1-pre
* OS: Windows
![image](https://user-images.githubusercontent.com/86514652/173051144-77cedd37-24b2-454b-a189-e53d6120cb3f.png)

**Comment by Gustry** [comment]
Confirmed, I will fix this asap
