### ISSUE TITLE
The QGIS Drag&Drop form in the popup is set to Automatic.

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [3liz/lizmap-plugin#429]
## Description
Selecting QGIS Drag&drop form with blank HTML maptips in QGIS will result in automatics behavior.

![image](https://user-images.githubusercontent.com/86514652/173380527-0b0e978a-9699-4591-a5cf-ec9fcc4e4d86.png)

## Context
* QGIS version: 3.226
* Lizmap version:3.4.11
* OS: windows
![image](https://user-images.githubusercontent.com/86514652/173379290-e8114348-7e8f-482e-9a49-fc136382b530.png)

**Comment by yamamoto-ryuzo** [comment]
Other behavior was as expected.

**Comment by Gustry** [comment]
Have you configured the Lizmap Web Client selector correctly ?

> Selecting QGIS Drag&drop

> Lizmap version:3.4.11

These two settings are incompatible. If you have your Lizmap Web Client version selector set correctly, the Drag&Drop form must be in blue.

**Comment by yamamoto-ryuzo** [comment]
That's exactly what I'm talking about.
If this happens, I will do my best to upgrade to 3.5.
I failed once with a 500 error, but I will try again.
Thank you very much.

**Comment by Gustry** [comment]
Thanks for feedback. 

If you have setup the Lizmap Web Client version target correctly in the dropdown menu, the "Form" item should in blue.
In blue, it's only for higher version of Lizmap Web Client.
