### ISSUE TITLE
Lizmap master

### ISSUE THREAD

**Issue by umbiz** [3liz/lizmap-plugin#44]
Hi, i'm testing lizmap 3.0pre, it's very good! 
If it may be useful:
when i create an user, the page http://10.110.1.4/lizmap-web-client-master/lizmap/www/admin.php/jauthdb_admin/default/savecreate   is
Application error - 'Error 500. A technical error has occured. Sorry for this trouble.'

**Comment by Gustry** [comment]
This issue should be raised on Lizmap web client repository.
