### ISSUE TITLE
Lizmap 2.11.2

### ISSUE THREAD

**Issue by umbiz** [3liz/lizmap-plugin#45]
Hi,
i have a problem with the latest release: in this project 
http://webgis.provincia.belluno.it/index.php/view/map/?repository=mappe&project=test3 
there are two layers (comuni = shape and the other is from PG), it's ok in 2.11.1

when i use it with 2.11.2
http://217.57.35.189/webgis_xx/index.php/view/map/?repository=mappe&project=test3
the shape layer doesn't appear and there isn't connection with db.

Thanks

**Comment by rldhont** [comment]
Hi @umbiz, 

The issue you encountered is due to the backoffice config. You reuse the subdomain of webgis.provincia.belluno.it in 217.57.35.189 and webgis_xx is not accessible on this domain.

Regards,

**Comment by umbiz** [comment]
Thanks for your help

**Comment by Gustry** [comment]
Closing, feel free to reopen.
