### ISSUE TITLE
Propose user to convert QGZ project to QGS

### ISSUE THREAD

**Issue by nicogodet** [3liz/lizmap-plugin#458]
Currently, if user want to open Lizmap on QGZ project, an error messagebox is displayed.
Even if the message is clear, adding a button "Convert to QGS" could be a nice to have

It could:

- open the "Save Project as..." dialog and let user choose 
- Do whatever "Save Project as..." does, keep current project name and don't ask anything to user (similar to a convert method but .QGZ still exists)

**Comment by Gustry** [comment]
> an error messagebox is displayed.

The messagebox doesn't not exist anymore.
Now anyone can open at least the first panel.

Honestly, it's -0 adding this button.
Some users will wonder why they `project.qgs` and `project.qgz` exists.

It's already the case, people will end with two files, but Lizmap is not the culprit, it's the end user who press the "saved as" button. We could again ask the question if they want to remove the previous one ... But I would prefer to let the user manage his files and being responsible for data loss or if the user edit the wrong file.

I think we have more dev to do on other tasks :)
