### ISSUE TITLE
the options for the visibility of the legends are lost

### ISSUE THREAD

**Issue by guenterw** [3liz/lizmap-plugin#464]
the options for the visibility of the legends are set back to the default value "Hide legend image at startup" every time the plugin is called.

* QGIS version:  3.22.14
* Lizmap version: 3.9.8 (Plugin)
* OS:  Win10 Pro

**Comment by Gustry** [comment]
Please follow the "right click" step https://docs.lizmap.com/current/en/publish/lizmap_plugin/information.html#request-for-support it gives us enough information to answer.
What is the branch selected in your first "information" panel ? It must be 3.6.

**Comment by guenterw** [comment]
branch is 3.6

![grafik](https://user-images.githubusercontent.com/8373176/209793936-1f216ac7-4e11-46f7-a826-b11b3a06ec7d.png)

But there is indeed (once) this error message:
![grafik](https://user-images.githubusercontent.com/8373176/209793870-fbd06fb4-fc95-44b0-b296-303eb67374b0.png)
When saving repeatedly, the message no longer appears

a reinstallation of the Lizmap plugin does not bring any change

**Comment by guenterw** [comment]
after many tests I can narrow down the problem.
It occurs only when the target version is 3.6.
With target version 3.5 everything is ok
![grafik](https://user-images.githubusercontent.com/8373176/209844779-afb48eac-9f43-435e-9725-9ad873205eb8.png)

Even if the project (fnp) is then displayed with Lizmap 3.6, everything is ok so far

The problem could be reproduced on a second computer. With target version 3.6 there is no error message but when calling the plugin again the default values for legend display are active again.

**Comment by Gustry** [comment]
For next time, please do the right click, "copy version for a support request". It gives us all necessary information, without the need to edit a screenshot.

> But there is indeed (once) this error message:

So there is something wrong somewhere in your backend settings ...

Please open your "logs panel", the small comic strip bubble on the right bottom corner and check Lizmap tab. (before opening a CFG, and when writing the CFG file. It will describe the process, especially with the key `noLegendImage` and/or `legend_image_option`.

> It occurs only when the target version is 3.6.
With target version 3.5 everything is ok

It's totally the reverse for me, which is expected.
The new key `legend_image_option` is only for LWC 3.6. For LWC 3.5 (and before), it's the legacy key `noLegendImage`. It works well for me.

So related to your message 
> But there is indeed (once) this error message:

and what you are describing, it seems your "backend version of LWC" is wrong.

In your QGIS settings, "advanced", "I will be careful", under the `lizmap` item, check the target verison of LWC.

I will dig into this bug.

**Comment by Gustry** [comment]
Can you try the development ZIP ? https://packages.3liz.org/pub/lizmap-qgis-plugin/unstable/

I have removed the usage of QSettings about the current LWC version and server. I'm not relying only on the combobox.

Commit 55236b33a928f097693fe34acf22d965b83f2e7b 07c38fbd4c8248acda2d5a512bfc006af4675f14 7209c3dffb707aeb85b1ffc3e0cff45f584cb74c

**Comment by guenterw** [comment]
I have installed the version 3.9.9. The error message when calling the plugin is gone.
But the legend visibility options are still reset to the default "Hide legend image at startup" when the plugin is invoked again.

> In your QGIS settings, "advanced", "I will be careful", under the lizmap item, check the target verison of LWC.
![grafik](https://user-images.githubusercontent.com/8373176/210263449-bd317326-dde7-4872-b637-468f57f5ec44.png)

logs panel:
![grafik](https://user-images.githubusercontent.com/8373176/210263716-79765871-74e1-48d8-a0ec-09bf1bb7eda8.png)
It is probably due to "Skipping key 'noLegendImage' because of max_version".

If I select "Disable the legend image" in the plugin and press "OK", then "legend_image_option": "disabled" is written to the cfg file. At the next plugin call the value is changed to "legend_image_option": "hide_at_startup" automatically.

**Comment by Gustry** [comment]
>  It is probably due to "Skipping key 'noLegendImage' because of max_version".

This one is normal, because `noLegendImage` is the legacy key LWC <= 3.5

Can you try again the latest package on your server ?
I would like to make a the release as soon as possible.

**Comment by guenterw** [comment]
I have tested the new version. Now the settings are preserved.
Everything is fine - thank you very much for the fast processing.

I still noticed that very(!) many, mostly identical messages written in the log (tab Lizmap) but is probably normal.

As written under [1] I would like to have such a function as for the legends also for the group settings and would like to participate in the costs.

[1] https://github.com/3liz/lizmap-web-client/issues/3052

**Comment by Gustry** [comment]
> I still noticed that very(!) many, mostly identical messages written in the log (tab Lizmap) but is probably normal.

Thanks for the note. I have noticed. This log is in a loop for **each** key so quite duplicated. I will make some cleaning.

> As written under [1] I would like to have such a function as for the legends also for the group settings and would like to participate in the costs.

We can have a look. I will come back to you.

I'm closing the ticket, I have released the version 3.9.9.
