### ISSUE TITLE
Check some legacy IGN layers

### ISSUE THREAD

**Issue by Gustry** [3liz/lizmap-plugin#471]
According to the new API in the news : https://geoservices.ign.fr/actualites/2023-01-23-geoplateforme

> Si vous êtes utilisateurs, utilisatrices des Géoservices, préparez-vous dès à présent au changement d’infrastructure. À compter de la fin du deuxième trimestre 2023, vous pourrez consommer vos Géoservices depuis l’infrastructure Géoplateforme. Nous attirons votre attention sur la date d’arrêt de l’infrastructure du Géoportail fixée au 31/12/2023 et nous vous invitons vivement à anticiper la mise en place des changements décrits ci-après.

I will make a ticket in LWC core.

**Comment by nworr** [comment]
Made some tests this day (2023-10-27) some layers are not available

As explained in https://geoservices.ign.fr/services-geoplateforme-diffusion 

> Attention, les couches "Cartes IGN", "Plan IGN" seront disponibles fin Octobre.

summary with example URL :  


| IGN Layer  | Status | URL |
| ----------- | ------------- | ----- |
| ORTHOIMAGERY.ORTHOPHOTOS  | ✅  | [sample](https://data.geopf.fr/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=ORTHOIMAGERY.ORTHOPHOTOS&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX=17&TILEROW=47860&TILECOL=66956&FORMAT=image%2Fjpeg) |
| CADASTRALPARCELS.PARCELLAIRE_EXPRESS  | ✅  | [sample](https://data.geopf.fr/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=CADASTRALPARCELS.PARCELLAIRE_EXPRESS&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX=17&TILEROW=47860&TILECOL=66956&FORMAT=image%2Fpng) |
|  GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2 | ❌  | [sample](https://data.geopf.fr/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX=17&TILEROW=47860&TILECOL=66956&FORMAT=image%2Fpng) |
| GEOGRAPHICALGRIDSYSTEMS.MAPS | ❌ | [sample](https://data.geopf.fr/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=GEOGRAPHICALGRIDSYSTEMS.MAPS&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX=17&TILEROW=47860&TILECOL=66956&FORMAT=image%2Fpng) |

Note : the sheet linked in the IGN page don't describe the "MAPS" layer
