### ISSUE TITLE
BUG - editable layer

### ISSUE THREAD

**Issue by manogenam** [3liz/lizmap-plugin#474]
## Description
Hi,
When I try to modify parameters on a layer that is already configured, I get a an error message "A duplicated "layerId"="mylayer" is already in the table". I have to delete it and completely reconfigure it.
## Context
* QGIS version: 
* 3.22.15
* Lizmap version:
* 3.10.0
* OS: 
* Windows 10

**Comment by Gustry** [comment]
Hi, it's already fixed in the next coming version.
