### ISSUE TITLE
Login and pwd shouldn't be mandatory in the information panel

### ISSUE THREAD

**Issue by RobiFag** [3liz/lizmap-plugin#475]
## Description
According to the plugin documentation (https://docs.lizmap.com/current/en/publish/lizmap_plugin/information.html), providing the user and password of Lizmap administrator  should be optional. But when I try to add a new server, the plugin returns the warning message "All fields are required" and I can't save the server if user and pwd are not provided.

![image](https://user-images.githubusercontent.com/25825472/218689969-f0e6eb46-d8a2-44ae-9253-6e81e3ce6563.png)

## Context
* QGIS version: 3.22.121
* Lizmap Plugin version: 3.10.1
* OS: Windows 10

**Comment by Gustry** [comment]
It's legacy in the documentation, it is now required as written in the plugin.

Fixed in the documentation https://github.com/3liz/lizmap-documentation/commit/9527142965a2a927d9629efc48f9877685c2f028

**Comment by RobiFag** [comment]
@Gustry here https://github.com/3liz/lizmap-documentation/commit/9527142965a2a927d9629efc48f9877685c2f028 you wrote that the user can be the administrator or a publisher but if I try to use a publisher user I got an error. Is it mandatory to use the lizmap admin user? and If I'm not the admin of Lizamp how can I publish a project?

**Comment by RobiFag** [comment]
I got this error:
![image](https://user-images.githubusercontent.com/25825472/218771952-17f8d850-7636-4c87-a47b-8053295af7c8.png)

It's a rights issue, checking the user rights in fact it doesn't have the lizmap admin access. If I grant this right to the user, the plugin is able to fetch metadata from lizmap instance.

**Comment by Gustry** [comment]
For 3.5, indeed, the right `lizmap.admin.access` is needed now. You should try a creating a user with only this right, there isn't too much he can do in the admin panel.
For 3.6, there is a new right **publisher** made for this purpose.

3.5.1 is very old with a lot of bug. We are now at 3.5.10, more than a year old already.

**Comment by RobiFag** [comment]
Thank you so much for the explanation @Gustry
