### ISSUE TITLE
form filter - type column

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-plugin#476]
## Description

type column appears empty:

![imagem](https://user-images.githubusercontent.com/10053874/221375834-e0af726d-412b-436f-8ef1-bff235c3e0d8.png)

## Context
* QGIS version: 3.22.16
* Lizmap version: 3.6.2 pre
* OS: Ubuntu 20

**Comment by Gustry** [comment]
It seems linked how the list is defined : d1bca9c5c1f626893001e5824196dec5fe9a6c9a

**Comment by Gustry** [comment]
The column is populated with the raw data, but the problem remains. The list must be moved in the definitions file (with icon, human display name etc)
