### ISSUE TITLE
address provider - google

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-plugin#477]
## Description
- this message appears when the user calls the plugin with an empty project
- this message also appears frequently even when exists an API key for google provider

![imagem](https://user-images.githubusercontent.com/10053874/221376200-35ad662d-ebc5-4a7f-8959-bcbe6c604ef4.png)

## Context
* QGIS version: 3.22.16
* Lizmap version: 3.6.2 pre
* OS: Ubuntu 20

**Comment by opbernardo** [comment]
Same thing here...

It is a bug?

I think, if, "Lizmap" needs the "Google API key" for "search functionality", then there must be a space where we can put this key that serves as the search key?

QGIS version: 3.22.4
Lizmap version: 3.5 - Stable
OS: Ubuntu 22

Thank you.

**Comment by Gustry** [comment]
I think it depends how the JSON is read.
From the CFG (when opening the plugin), if google is activated before the Google key is set, it will trigger this warning.

I will try to have a look to disable the check when reading the CFG file.

**Comment by opbernardo** [comment]
Hi @Gustry,
Thank you very much.
Best regards

**Comment by opbernardo** [comment]
I 'm using 3.10.1 version...
![Screenshot from 2023-03-09 16-25-33](https://user-images.githubusercontent.com/15649016/224087872-a736db72-7c72-4e98-a3f5-fcdb985fcc11.png)
