### ISSUE TITLE
dataviz - html template/error

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-plugin#484]
when the user has a html template chart and click oh button:

![imagem](https://user-images.githubusercontent.com/10053874/226199146-ebf55353-d396-4d0c-bf8a-5d8ddb47324f.png)

**Comment by Gustry** [comment]
Already fixed : 485d36d5d980480f81f47fafedd720bd4adfc870

**Comment by Antoviscomi** [comment]
@Gustry  after the apply of your fix, the error disappeared now,  but there no graph il popup, I reath the html code of my template, and noth the graèh I expetted to see
look at the below screenshot

![Schermata del 2023-03-20 14-24-11](https://user-images.githubusercontent.com/12639444/226353462-a73a2da8-096d-4d22-b3ee-ff6203ffe367.png)

**Comment by Gustry** [comment]
Please create a separate issue following the ticket template, showing your plot configuration (is-it really HTML based like this ticket, it looks like plotly based).

**Comment by Antoviscomi** [comment]
> Please create a separate issue following the ticket template, showing your plot configuration (is-it really HTML based like this ticket, it looks like plotly based).

This code it's a plotly output, however  I'll create another issue if you need

**Comment by Antoviscomi** [comment]
Sorry @Gustry it works fine pasting Data Plotly in the correct way
