### ISSUE TITLE
Lizmap Plugin 3.11.3 causes a Python Warning on Apply configurations

### ISSUE THREAD

**Issue by Antoviscomi** [3liz/lizmap-plugin#487]
### What is the bug?

@Gustry Hi Etienne,
I noticed that,
when I go to apply my settings on a .qgs project I receive the following Python Warning message:
 
_WARNING    Traceback (most recent call last):
              File "/home/antonio/.local/share/QGIS/QGIS3/profiles/default/python/plugins/lizmap/plugin.py", line 2290, in setItemOptions
              self.dlg.relation_stacked_widget.setCurrentWidget(self.dlg.page_no_relation)
             AttributeError: 'LizmapDialog' object has no attribute 'page_no_relation'_

### Versions

**Versions :**

* Lizmap Web Client : 3.6.2
* Lizmap Web Client target version : 3.6
* Lizmap plugin : 3.11.3
* QGIS Desktop : 3.30.1
* QGIS Server : 3.30.1
* Py-QGIS-Server : not used
* QGIS Server plugin DataPlotly : 3.9.2
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 2.7.0
* QGIS Server plugin wfsOutputExtension : 1.7.1

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

**Comment by Gustry** [comment]
Thanks, it seems a I failed to merge a git conflict when merging.
The zip package is available (in a few minutes) on https://packages.3liz.org/pub/lizmap-qgis-plugin/unstable/ if you wanna try

**Comment by Antoviscomi** [comment]
@Gustry it seems to works fine now

**Comment by Gustry** [comment]
The release is public, without the manual install.

**Comment by Antoviscomi** [comment]
@Gustry  I'd just installed it via plugin manager, many thanks Étienne
