### ISSUE TITLE
[Bug]: unknown plugins on qgis server

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-plugin#490]
### What is the bug?

lizmap plugin can't detect information about plugins installed on qgis server
![imagem](https://user-images.githubusercontent.com/10053874/232744565-035cbe89-5392-4b6f-bfed-591c45e51ecb.png)

qgis server information:
![imagem](https://user-images.githubusercontent.com/10053874/232745057-e0ee9708-d87a-4e5c-86da-a780528f7df6.png)

### Versions

**Versions :**

* Lizmap Web Client : 3.6.2
* Lizmap Web Client target version : 3.7
* Lizmap plugin : 3.11.5
* QGIS Desktop : 3.22.16
* QGIS Server : 3.22.16
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 2.7.1
* QGIS Server plugin wfsOutputExtension : 1.7.1

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

**Comment by josemvm** [comment]
@Gustry thanks for your clarification! :-)

**Comment by Gustry** [comment]
I kept the the ticket open, this API issue with the QGIS native plugin manager must be fixed or hidden...

**Comment by Gustry** [comment]
I didn't mean fixed, but related.

**Comment by arno974** [comment]
@Gustry Why if the extensions version are correctly identified if the support message from Lizmap plugin, these informations are not displayed on the plugin interface ?

(Information TAB)
Lizmap - Unknown
WfsOutputExtension - Unknow
AtlasPrint - Unknow

**Comment by Gustry** [comment]
@arno974 

> These labels are for official released versions on https://plugins.qgis.org/ Unfortunetaly, the public API of the QGIS plugin manager is not a very good shape for now...

It's designed for latest release available on https://plugins.qgis.org
But, it's hidden now since the latest release.
