### ISSUE TITLE
[Bug]: UX problem on Map Option Tab

### ISSUE THREAD

**Issue by arno974** [3liz/lizmap-plugin#492]
### What is the bug?

The UX for the content of the Map option tab seems to have a problem. I've a updated my Lizmap plugin and since then I have a very long horizontal scrollbar (only for Map Option).

![image](https://user-images.githubusercontent.com/425243/233257823-21fcdbf2-2b45-4f6a-8e49-cb92c131c62e.png)

### Versions

**Versions :**

* Lizmap Web Client : 3.6.3
* Lizmap Web Client target version : 3.6
* Lizmap plugin : 3.11.5
* QGIS Desktop : 3.26.3
* QGIS Server : 3.22.7
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : not found
* QGIS Server plugin lizmap_server : 2.7.1
* QGIS Server plugin wfsOutputExtension : not found

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

**Comment by Gustry** [comment]
> Lizmap plugin : 3.11.5

It's not the latest one. This bug has already been fixed and released ;-)

**Comment by Gustry** [comment]
https://github.com/3liz/lizmap-plugin/releases

There is a release every week, so it should be like a weekly routine now ... update lizmap plugin :D

No worries
