### ISSUE TITLE
[Bug]: the plugin lost ability to save html code

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-plugin#495]
### What is the bug?

html code is not saved in the cfg file for any layer abstract
this is a regression

### Versions

**Versions :**

* Lizmap Web Client : 3.6.2
* Lizmap plugin : 3.12.0
* QGIS Desktop : 3.22.16
* QGIS Server : 3.22.16
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 2.7.1
* QGIS Server plugin wfsOutputExtension : 1.7.1

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

**Comment by Gustry** [comment]
I don't replicate, neither from a graphical test in QGIS desktop nor a unit test I just added in the commit above.
I would need more details. Do you have any duplicated layers with same name ?

**Comment by josemvm** [comment]
>Do you have any duplicated layers with same name ?

no

**Comment by josemvm** [comment]
sorry, this is a particular case concerning a (valid) project...
