### ISSUE TITLE
dtaviz - drag & drop layout - remove plot from layout button

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-plugin#499]
hi @Gustry 

i think it needs a button for remove plot from layout:
![imagem](https://github.com/3liz/lizmap-plugin/assets/10053874/da34c014-c01c-4052-8dc3-3a3c0019be1c)

thanks

**Comment by Gustry** [comment]
Yes, it was planned ;-) 
As 3.7.0 is not out yet, so it's still under development.
The button is already there in the code, but just hidden to avoid you a crash : https://github.com/3liz/lizmap-plugin/blob/master/lizmap/drag_drop_dataviz_manager.py#L73
