### ISSUE TITLE
[Bug]: HTML generated tries to concatenate on numeric fields, resulting in invalid expression and no data displayed

### ISSUE THREAD

**Issue by u-cav** [3liz/lizmap-plugin#501]
### What is the bug?

When a layer contains a value relation where the value column is numeric, the HTML generated by the Lizmap plugin (both with the QGIS HTML maptip or with QGIS Drag&Drop Form), contains this expression:
```
CASE
                        WHEN "fid_supplyzone" IS NOT NULL OR trim("fid_supplyzone") != ''
                        THEN concat(
                            '<p>', '<b>Distretto</b>',
                            '<div class="field">', 
                    aggregate(
                        layer:='wa_supplyzone_1a565788_09e8_404b_93e1_74b92cf6ac2f',
                        aggregate:='concatenate',
                        expression:="fid",
                        filter:="fid" = attribute(@parent, 'fid_supplyzone')
                    ), '</div>',
                            '</p>'
                        )
                        ELSE ''
                    END
```
Resulting in this being shown on lizmap-web-client, and on the QGIS HTML maptip:
![2023-06-06_11-24](https://github.com/3liz/lizmap-plugin/assets/4831528/b264c171-a666-4f0c-92c7-f88f10a26cb9)

When pasting the expression in the field calculator, the following error is thrown:

```Eval Error: Could not calculate aggregate for: fid (Cannot calculate concatenate on numeric fields)```

Modifying the HTML to convert the fid to string works:
```
CASE
                        WHEN "fid_supplyzone" IS NOT NULL OR trim("fid_supplyzone") != ''
                        THEN concat(
                            '<p>', '<b>Distretto</b>',
                            '<div class="field">', 
                    aggregate(
                        layer:='wa_supplyzone_1a565788_09e8_404b_93e1_74b92cf6ac2f',
                        aggregate:='concatenate',
                        expression:=to_string("fid"),
                        filter:="fid" = attribute(@parent, 'fid_supplyzone')
                    ), '</div>',
                            '</p>'
                        )
                        ELSE ''
                    END
```

This workaround is not possible when using the new QGIS Drag&Drop Form on Lizmap.

### Versions

**Versions :**

* Lizmap Web Client : 3.6.3
* Lizmap plugin : 3.14.0
* QGIS Desktop : 3.28.6
* QGIS Server : 3.28.3
* Py-QGIS-Server : 1.8.7
* QGIS Server plugin atlasprint : not found
* QGIS Server plugin lizmap_server : 2.7.1
* QGIS Server plugin wfsOutputExtension : 1.7.1

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

**Comment by ghtmtt** [comment]
@Gustry a quick solution could be to always convert the `expression` parameter of https://github.com/3liz/lizmap-plugin/blob/03f2263dbbf840d0c9b5241dcb82847ff9d43bd6/lizmap/tooltip.py#L211 to a string:

```python
expression:=to_string({})
```

because the error is related to the `concatenate` aggregation function not able to concatenate numbers. What do you think?
