### ISSUE TITLE
Can not login on server via Lizmap plugin  

### ISSUE THREAD

**Issue by meyerlor** [3liz/lizmap-plugin#504]
## Description
I just installed Lizmap 3.6.4 on a Ubuntu 20.04 Server. QGIS/QGIS-Server version 3.22. When i login via the webbrowser, under "Server Information" i can see that the connection to the QGIS server seems to work (It shows my installed plugins as well as the version number of QGIS server). 
I created a new user with admin rights . The user is saved so lizmap can actually write into the user-database.

Now in the QGIS plugin when i fill in the "http://123.456.78.9/lizmap/ and continue to give the username/pwd it is always saying 
"The given user does not have the right. **View the detailed server information**"

Right: lizmap.admin.server.information.view"

It strangely does not matter, if i use any of the admin users i created. Even if i type phantasy usernames/pwd it comes up with the same message. Any idea, what could be the issu?

![grafik](https://github.com/3liz/lizmap-plugin/assets/15894401/e90a4ba4-803d-4ec9-9841-f20464a0cab8)

## Context
* QGIS version:
* Lizmap version:
* OS:

**Comment by meyerlor** [comment]
thanks for coming back to me!

I followed your steps, this json is what i get 

{"info":{"version":"3.6.4","date":"2023-05-30"},"dependencies":{"jelix":{"version":"1.8.1","minversion":"1.8.1","maxversion":"1.8.1"}},"api":{"dataviz":{"version":"1.0.0"}},"repositories":{"2":{"label":"Demo-Projekt 06\/23","path":"test\/","authorized_groups":["__anonymous","admins","publishers","users"],"editing_authorized_groups":["admins"],"projects":[]}},"acl":{"groups":{"publishers":{"label":"Publishers"},"admins":{"label":"admins"},"users":{"label":"users"}}},"qgis_server_info":{"metadata":{"commit_id":"6f08e4d7b0","name":"Bia\u0142owie\u017ca","py_qgis_server":false,"py_qgis_server_version":"not used","tag":"final-3_22_16","version":"3.22.16","version_int":32216},"plugins":{"atlasprint":{"commitNumber":"1","commitSha1":"7b8a3ea12775bcdcdac0b0f8432bd64adb3dc528","dateTime":"2022-10-19T08:10:14Z","name":"atlasprint","repository":"https:\/\/github.com\/3liz\/qgis-atlasprint","version":"3.3.2"},"lizmap_server":{"commitNumber":"1","commitSha1":"1fb453e7bac62af1f7d94bffe3a0242b28debe4d","dateTime":"2023-05-30T12:20:05Z","name":"Lizmap server","repository":"https:\/\/github.com\/3liz\/qgis-lizmap-server-plugin","version":"2.7.2"},"wfsOutputExtension":{"name":"wfsOutputExtension","version":"not found"}},"py_qgis_server":{"build_id":null,"commit_id":null,"found":false,"stable":false,"stable_release":false,"version":"not used"},"services":["WMS","WFS","WCS","WMTS","ATLAS","EXPRESSION","LIZMAP"]}}

**Comment by Gustry** [comment]
Ok, but this is correct result.

If you use this server URL `http://123.456.78.9/lizmap/`, login `admin` and password, it's not working in QGIS desktop ?

**Comment by Gustry** [comment]
Was it a fresh install or an old Lizmap Web Client installation and you upgraded it ? (if upgraded, when did you install it ?)

**Comment by meyerlor** [comment]
It was a fresh install on Ubuntu Server 22.04

I'm using SQlite for storing the users/groups

**Comment by Gustry** [comment]
Did you double check my comment ? https://github.com/3liz/lizmap-plugin/issues/504#issuecomment-1630749708

The result is your webbrowser is fine.
Can you debug from your computer using wget/curl or similar using HTTP basic auth for login and password with the URL `http://123.456.78.9/lizmap/index.php/view/app/metadata` ?

**Comment by meyerlor** [comment]
sorry, i overlooked your comment - yes, exactly that is the case. I fill in the same admin/pw credentials i use via the web-interface and get the message from https://github.com/3liz/lizmap-plugin/issues/504#issue-1769044050

I will try with a completely fresh install next week, maybe i set up something wrong during installation process (unix read/write rights..?)

**Comment by Gustry** [comment]
> I will try with a completely fresh install next week

Not necessary.

If you can try with curl/wget (CLI on linux) or Postman (in your webbrowser) to make the HTTP request with your Basic auth.

**Comment by meyerlor** [comment]
Sorry, i had to seetup the server new due to other reasons as well :/ - if the problem comes up again, i will report further!

**Comment by Gustry** [comment]
So it means it's resolved ?
Ok, so we might still have the bug somewhere. Closing for now, feel free to reopen.

**Comment by vitorcricas** [comment]
Happened to me too! 
In my case it was because i was using php8.1 with PHP-FPM & FastCGI
