### ISSUE TITLE
Changes in D&D form do not trigger LM plugin to regenerate its own used for the popup dialog

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-plugin#506]
### What is the bug?

Changes in D&D form do not trigger LM plugin to regenerate its own definition used for the popup dialog, so it is necessary to first change the type of popup, then choose again D&D again.

I guess it would be better the plugin to re-generate its own D&D definitions each time the plugin is opened, so to re-read eventual changes in QGIS project.

### Versions

3.14.2

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

**Comment by Gustry** [comment]
Which kind of popup are you using ?
In both "QGIS HTML maptip" or "Form", there isn't any copy of the DD layout.

There is only a "copy the drag&drop form layout" for the "HTML maptip" one, and it's not synchronize on purpose. This button is only a helper to start with an empty HTML layout.

**Comment by gioman** [comment]
> Which kind of popup are you using ?

@Gustry 

![image](https://github.com/3liz/lizmap-plugin/assets/1951107/6817770e-f110-4cb9-a623-8aaa2063d2a5)

**Comment by Gustry** [comment]
There isn't any copy of the drag and drop form when using this button. It's only n the server side that the QGS file is read.

> so it is necessary to first change the type of popup, then choose again D&D again.

Please do a "diff" on the CFG file, before/after, you shouldn't have any by doing that related to the current D&D layout.

The maptip is only replaced on the server side, on the fly : https://github.com/3liz/qgis-lizmap-server-plugin/blob/master/lizmap_server/get_feature_info.py

Maybe use debug mode in your logs in QGIS server, and there will be a clue ?

Can you please do the step in the Lizmap plugin ? It's quick to do, but it helps us. I don't know if you are using Py-QGIS-Server, which versions you are using etc ...

**Comment by gioman** [comment]
Is not the first time that re-testing one day after observing something gives me different/expected results (see my ticket about seeding/caching for example). Sorry for the noise.
