### ISSUE TITLE
New HTML editor for abstracts does not open for groups

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-plugin#509]
### What is the bug?

While it opens correctly for layers.

### Versions

Latest LM plugin.

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

**Comment by Gustry** [comment]
Thanks, indeed.
It has been fixed.
