### ISSUE TITLE
Probléme lizmap popup configuration avancé

### ISSUE THREAD

**Issue by clementPar** [3liz/lizmap-plugin#51]
Bonjour à tous,
tout d'abord merci pour votre outils très opérationnel.
Je me tourne vers suite à un problème rencontré lors du paramétrage avancé des popups.
Lorsque je crée un popup en html du type :
"<p> Nom de la structure : {$Nom de la structure :}</p>"
....
...

Le popup en question m'affiche systématiquement la valeur d'un colonne située plus loin dans mon fichier de données.
J'ai vérifié maintes et maintes fois l'intégrité de mon fichiers csv, et tout à l'air bien de ce coté la.
Je précise que je travail à partir d'un fichier de point (csv) pour facilité la mise à jour des données par la suite, qui sera géré par des non géomaticiens. 
Mon fichier csv est composé d'une cinquantaine de champs de tout type.Les travaux de requête sous qgis se passe sans aucuns problème, tout comme la visualisation en ligne. 
Lorsque je teste avec un fichier de test tout petit composé de deux ou trois colonnes,la génération du popup se déroule correctement, de même que si je génère un popup simple, il me charge correctement l'ensemble de ma table dans la popup.

Voila , maintenant je sèche et j'ai l'impression d'avoir tout testé...

Merci d'avance pour votre aide.

Clément

**Comment by nboisteault** [comment]
Bonjour,
Comment s'appelle le nom de la colonne que vous voulez afficher dans la popup?
Dans votre question "Nom de la structure :" me parait étrange.

**Comment by clementPar** [comment]
le nom s'appelle bien "Nom de la structure :",
J'ai testé en renommant cette colonne sans espace ni caractère spéciaux, sans succès...

**Comment by clementPar** [comment]
Bonjour,
je me permet de répondre à ce sujet.
C'est effectivement une erreur de débutant de ma part, avec la présence d'un caractère spéciaux dans mes entêtes de colonne (tiret du 6....) ...

J'ai maintenant une seconde question, pouvez vous m'indiquez dans quelle script peut on gérer l'emplacement dans la fenêtre des infobulles générées?
En effet certaines s'affiche sous la bar de la légende et cela gêne leur bonne lecture.

Clément

**Comment by nboisteault** [comment]
Pouvez-vous faire une capture d'écran pour illustrer votre problème?

**Comment by clementPar** [comment]
![infobulle](https://cloud.githubusercontent.com/assets/16706271/12420313/3832e1ec-bebc-11e5-8101-c99f64338ebf.JPG)
Voici une illustration de l'affichage d'une infobulle masquée. J'aimerais par exemple, faire pour quelle s'affiche toujour à droite de la selection

**Comment by rldhont** [comment]
En fait dans lwc3 la carte occupe toute la page. Elle est donc aussi en dessous du panneau des couches. Comme les popups sont des éléments de la carte, elle passe en dessous de tous les panneaux afficher.

**Comment by clementPar** [comment]
Ok, je comprend le problème. Il faut donc que j'adapte la taille de la carte

**Comment by rldhont** [comment]
Êtes vous en train de modifier les scripts JS de Lizmap pour coller à vos besoisn ?

La solution serait plutôt de définir un comportement qui conviennent.
Par exemple, fermer le panneau des couches à l'affichage d'une popup ?

**Comment by clementPar** [comment]
Non pas encore j'essaie de comprendre comment cela fonctionne.... ;)
en faire j'aimerais pouvoir afficher ma carte comme sur cet exemple.... : 
http://carto.aduga.org/index.php/view/map/?repository=observatoire&project=friche_grd_amienois

**Comment by rldhont** [comment]
Pour cela utilisé plutôt la version 2.12.

Par contre la nouvelle structure de page ne vous convient pas ?

**Comment by clementPar** [comment]
Si bien sur, je l'a trouve top!
C'est juste cette histoire de taille de carte pour l'affichage de la légende qui me dérange...

**Comment by clementPar** [comment]
Savez vous si je peux adapter la taille de la carte en fonction de la place prise par la légende?ou comme vous me le suggériez de fermer la barre de légende à l'ouverture d'une popup?
Merci d'avance

**Comment by mdouchin** [comment]
Je viens d'ajouter (dans la future lizmap 3) et dans le plugin version "master" la possibilité de choisir où se place le contenu de la popup: on pourra donc facilement choisir si la popup apparaît:
* sur la carte comme actuellement
* dans le panneau de gauche ( dock )
* dans le panneau d'information (en haut à droite = mini-dock)

**Comment by Gustry** [comment]
Is this still valid ?
There are a lot of dev since version 2.12

If so, I think the ticket should transfered on the LWC side. It's not linked to the plugin side.

**Comment by Gustry** [comment]
Closing for lack of feedback.

There were a lot of improvements on this side. And Lizmap popup is deprecated for vector layers.
