### ISSUE TITLE
API key error if IGN selected as address provider even if key is provided

### ISSUE THREAD

**Issue by nicogodet** [3liz/lizmap-plugin#513]
### What is the bug?

![image](https://github.com/3liz/lizmap-plugin/assets/39594821/563ba4fd-c3a7-4294-a2d6-59ecade84a6d)

It pops every time I open plugin even if API key is provided in base map tab.
![image](https://github.com/3liz/lizmap-plugin/assets/39594821/5562cc0f-442d-413b-8fa8-ecd54a3d3a9e)

### Versions

**Versions :**

* Lizmap Web Client : 3.6.5
* Lizmap plugin : 3.16.3
* QGIS Desktop : 3.28.9
* QGIS Server : 3.28.9
* Py-QGIS-Server : 1.8.8
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 2.8.0
* QGIS Server plugin wfsOutputExtension : 1.8.0

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

**Comment by nicogodet** [comment]
Open Lizmap
![image](https://github.com/3liz/lizmap-plugin/assets/39594821/2e7f86ed-83cd-4f0d-86f0-381c099d2cb4)
Press OK
![image](https://github.com/3liz/lizmap-plugin/assets/39594821/b6c4c349-7737-4041-960b-f1a0df2fdde1)

Check triggered too soon ?

**Comment by Gustry** [comment]
Not dirty, it looks correct ;-)
You can see indeed the previous commit was like very similar :D

**Comment by nicogodet** [comment]
I made these changes locally, I just would like to test a bit before you push next release ;)
