### ISSUE TITLE
[Freeze Behavior] Configure Layer Popup with html syntax

### ISSUE THREAD

**Issue by jonnyforestGIS** [3liz/lizmap-plugin#52]
Hi,
using a postgis layer with more then 20 fields when i try to configure the Layer Popup and show more then 7 fields the dialog starts to freeze and slowdown the type.

Suggestion:
[Feature request]: Option in configure layer popup to load external file .html or .txt with the confguration popup of the layer.

Regards
João

**Comment by Gustry** [comment]
* Lizmap popup is deprecated for a few versions now.
* Creating a QGIS HTML maptip from the Lizmap plugin is now generating the HTML for all fields if you want.
