### ISSUE TITLE
lizmap qgis plugin version =>4 error at czech locale[Bug]: 

### ISSUE THREAD

**Issue by gisgogo** [3liz/lizmap-plugin#543]
### What is the bug?

Lizmap qgis plugin version =>4 generate error at czech locales of qgis. 
error: Files must be located in {folder} or in a sub directory. Is translated key {folder} to czech lang.
plugins\lizmap\dialogs\main.py, line 279 - 280

KeyError: 'adresáři' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.13/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/gogo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lizmap\__init__.py", line 9, in classFactory
    return Lizmap(iface)
  File "C:\Users/gogo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lizmap\plugin.py", line 270, in __init__
    self.dlg = LizmapDialog(is_dev_version=self.is_dev_version, lwc_version=self._version)
  File "C:\Users/gogo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lizmap\dialogs\main.py", line 279, in __init__
    self.radio_force_local_folder.setToolTip(tr(
KeyError: 'adresáři'

Verze Pythonu: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS verze: 3.28.13-Firenze Firenze, 3b4db4f561 

### Versions

4

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

**Comment by Gustry** [comment]
Next time, you should edit the string in Transifex. https://app.transifex.com/3liz-1/lizmap-locales/dashboard/
As I don't speak czech, it would be easier for you, and can finish translations (only 11 strings missing for the plugin side)

All strings between `{}` mustn't be translated.

Is-it `Files must be located in {folder} or in a sub directory.` → `Soubory musí být umístěny v {folder} nebo v podadresáři.` ?

**Comment by Gustry** [comment]
Gentle ping @gisgogo COuld you fix the issue in Transifex ?

**Comment by Gustry** [comment]
CLosing for lack of feedback, I hope you fixed it in Transifex.
