### ISSUE TITLE
Selection du "Fond de carte actif au démarrage"

### ISSUE THREAD

**Issue by geoek** [3liz/lizmap-plugin#56]
Je viens de remarquer un petit bug dans le plugin : à l'ouverture du plugin, la sélection du fond de carte actif au démarrage (option rajouté récemment) est réinitialisé à la première valeur. Il faut donc le modifier à chaque fois.

**Comment by mdouchin** [comment]
fixed in b1210aeaf50eda804b2fbb1626266b3de6ad9f10 Can you check and report back ?

**Comment by Gustry** [comment]
I'm closing this issue as it seems fixed already.
