### ISSUE TITLE
[Bug]: Saved extent is not valid in CFG

### ISSUE THREAD

**Issue by tbnobody** [3liz/lizmap-plugin#571]
### What is the bug?

I just saved a new configuration of a project and the project failed to parse:
```
2024-03-13 16:16:19     10.140.129.6    [0]     The file /opt/qgis/lizmap/projects/ProjectOverview.qgs.cfg cannot be decoded.    /var/www/lizmap-web-client-3.7.5/lizmap/modules/lizmap/lib/Project/Project.php     135
        /lizmap/admin.php/admin/qgis_projects
array (   'module' => 'admin',   'action' => 'qgis_projects:index', )

        0       Lizmap\Project\Project->__construct()   /var/www/lizmap-web-client-3.7.5/lizmap/modules/lizmap/lib/Project/Repository.php : 294
        1       Lizmap\Project\Repository->getProject() /var/www/lizmap-web-client-3.7.5/lizmap/modules/lizmap/lib/Project/Repository.php : 388
        2       Lizmap\Project\Repository->getProjectsMetadata()        /var/www/lizmap-web-client-3.7.5/lizmap/modules/lizmap/classes/lizmapRepository.class.php : 166
        3       lizmapRepository->getProjectsMetadata() /var/www/lizmap-web-client-3.7.5/lizmap/modules/admin/zones/project_list.zone.php : 43
        4       project_listZone->_prepareTpl() /var/www/lizmap-web-client-3.7.5/lizmap/vendor/jelix/jelix/lib/jelix/utils/jZone.class.php : 282
        5       jZone->_createContent() /var/www/lizmap-web-client-3.7.5/lizmap/vendor/jelix/jelix/lib/jelix/utils/jZone.class.php : 217
        6       jZone->getContent()     /var/www/lizmap-web-client-3.7.5/lizmap/vendor/jelix/jelix/lib/jelix/utils/jZone.class.php : 373
        7       jZone::_callZone()      /var/www/lizmap-web-client-3.7.5/lizmap/vendor/jelix/jelix/lib/jelix/utils/jZone.class.php : 114
        8       jZone::get()    /var/www/lizmap-web-client-3.7.5/lizmap/modules/admin/controllers/qgis_projects.classic.php : 31
        9       qgis_projectsCtrl->index()      /var/www/lizmap-web-client-3.7.5/lizmap/vendor/jelix/jelix/lib/jelix/core/jCoordinator.class.php : 266
        10      jCoordinator->process() /var/www/lizmap-web-client-3.7.5/lizmap/www/admin.php : 23
```

For some layers I see the following in the json code:
```json
        "Offices": {
            "id": "Offices_3e456444_b7b3_4ed5_b24e_f67e35c952d4",
            "name": "Offices",
            "type": "layer",
            "geometryType": "point",
            "extent": [
                NaN,
                NaN,
                NaN,
                NaN
            ],
            "crs": "EPSG:4326",
            "title": "Offices",
            "abstract": "",
            "link": "",
            "minScale": 1,
            "maxScale": 1000000000000,
            "toggled": "False",
            "popup": "True",
            "popupSource": "form",
            "popupTemplate": "",
            "popupMaxFeatures": 10,
            "popupDisplayChildren": "False",
            "popup_allow_download": true,
            "legend_image_option": "hide_at_startup",
            "groupAsLayer": "False",
            "baseLayer": "False",
            "displayInLegend": "True",
            "group_visibility": [],
            "singleTile": "True",
            "imageFormat": "image/png",
            "cached": "False",
            "clientCacheExpiration": 300
        },
```

The NAN is invalid.

### Versions, safeguards, checks summary etc

**Versions :**

* Lizmap Web Client : 3.7.5
* Lizmap plugin : 4.2.7
* QGIS Desktop : 3.36.0
* QGIS Server : 3.36.0
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : not found
* QGIS Server plugin lizmap_server : 2.8.4
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : safe
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

**Comment by tbnobody** [comment]
Don't know where the error came from but after pressing this button for all affected layers it's working now:
![grafik](https://github.com/3liz/lizmap-plugin/assets/1753222/9e938051-a5c8-4a64-814f-3ee79480e5a4)

**Comment by tbnobody** [comment]
Ok just figured it out.... 
* Opened the extension, pressed "Save"
* NaN in json
* go to layers, press "Update" button
* go to lizmap extension, press "Save"
* Correct coordinates in json
* go to lizmap extension, press "Save"
* NaN in json

**Comment by Gustry** [comment]
>go to lizmap extension, press "Save"
Correct coordinates in json
go to lizmap extension, press "Save"
NaN in json

Do you mean you press twice ? Because there isn't any user action in between these two.

What kind of layer is `Offices` ? PH, SHP, GPKG ? Is-it possible to share it ?
I will just add a safeguards for now

**Comment by Gustry** [comment]
In your vector layer properties → Information tab → Provider, what is the "Extent" here ? The plugin is taking these values.

**Comment by tbnobody** [comment]
> Do you mean you press twice ?

Correct, just closed the extension window and opened it again

> What kind of layer is Offices ?

It's PostGIS

> In your vector layer properties → Information tab → Provider, what is the "Extent" here ?

You are right, it's shown as `Null`
![grafik](https://github.com/3liz/lizmap-plugin/assets/1753222/547505ca-4929-40a7-8e83-f9f9fe46b27c)

**Comment by Gustry** [comment]
Even QGIS can't get the correct extent of your layer.

Side question can you select if in your legend and then Python → COnsole

```python
iface.activeLayer().extent().isNull()
iface.activeLayer().extent().isEmpty()
```
And give the output of these two commands ?

**Comment by tbnobody** [comment]
> And give the output of these two commands ?

Both return `True`

**Comment by tbnobody** [comment]
Just found this: https://github.com/qgis/QGIS/issues/56541

**Comment by Gustry** [comment]
It seems it will be fixed upstream.
