### ISSUE TITLE
Do not allow getting images from a WMS server for non WMS layers

### ISSUE THREAD

**Issue by pcav** [3liz/lizmap-plugin#58]
If I select, in the plugin, `Get images directly from external WMS` for a non WMS layer, the project is broken in Lizmap web client
I suggest to deactivate that option for the layers other than WMS.
￼
See also: https://github.com/3liz/lizmap-web-client/issues/306

**Comment by mdouchin** [comment]
done via  391e79a

**Comment by rldhont** [comment]
@mdouchin the commit you linked does not fix this issue.

**Comment by rldhont** [comment]
Fixed with efdd994e4d757a6c6f8ff538ab123754bbc854a4
Sorry for the noise.
