### ISSUE TITLE
Correct entry of the Google API key

### ISSUE THREAD

**Issue by guenterw** [3liz/lizmap-plugin#585]
Since qgis plugin version 4.3.15 the Google key is required in the plugin. Previously, this was sufficient in the JS script (GoogleStreetView.js)
Is the input in this form correct?

![image](https://github.com/3liz/lizmap-web-client/assets/8373176/c9efa41f-455e-44ef-b9b3-8dc1df824e22)

I still get the error message:

![image](https://github.com/3liz/lizmap-web-client/assets/8373176/e3cb86d4-04cc-4a46-8987-773be4dd9e70)

It does not work with 'xxx' either. Is this user error or bug?
The JS script GoogleStreetView.js still works as usual in version 3.6.13 and 3.7.8

**Comment by Gustry** [comment]
Indeed, that's was a bug.
It's mainly related to the new server version https://github.com/3liz/qgis-lizmap-server-plugin/releases/tag/2.9.4 which is checking API keys and discard layers if needed.
