### ISSUE TITLE
[Bug]: OSM layer comes with zoom min/max defined

### ISSUE THREAD

**Issue by nboisteault** [3liz/lizmap-plugin#586]
### What is the bug?

Users might want to zoom above the zoom max defined to 19 via upscalling. So we should let them define those values.
https://github.com/3liz/lizmap-plugin/blob/eb6048086b50cc54f76498ecace3a428b211f4b7/lizmap/plugin.py#L2665

### Versions, safeguards, checks summary etc

**Versions :**

* Lizmap Web Client : 3.9.0-pre
* Lizmap plugin : master
* QGIS Desktop : 3.28.15
* QGIS Server : 3.28.13
* Py-QGIS-Server : 1.8.8
* QGIS Server plugin atlasprint : 3.4.2-alpha
* QGIS Server plugin lizmap_server : 2.9.5-alpha
* QGIS Server plugin tilesForServer : master
* QGIS Server plugin wfsOutputExtension : 1.8.2-alpha

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : yes
* Number of parent : 2 folder(s)
* Prevent other drive : yes
* Prevent PG service : no
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

**Comment by Gustry** [comment]
Is that OK @nboisteault ? CF commit https://github.com/3liz/lizmap-plugin/commit/f6e2a94cf06985944e537b528264b72799f2ad92

**Comment by Gustry** [comment]
Mainly linked to https://github.com/3liz/lizmap-web-client/issues/4332

>  So we should let them define those values.

This is possible in QGIS desktop raster layer properties UI. I'm not going to rewrite QGIS desktop settings :)

**Comment by nboisteault** [comment]
@Gustry It is ok for me. We might go back later but it needs some discussion with @rldhont
