### ISSUE TITLE
[Bug]: V4.3.22 WMS service direct from server does not work

### ISSUE THREAD

**Issue by guenterw** [3liz/lizmap-plugin#599]
### What is the bug?

WMS services that are integrated with the ‘Get images directly from server (Request directly)’ option are not displayed in the WebClient.
![image](https://github.com/user-attachments/assets/8b050e00-5cd2-40a6-aa6a-597fd70ba66a)

With version 4.3.21 they are displayed as usual.
After downgrading to 4.3.21 everything is ok again

### Versions, safeguards, checks summary etc

**Versions :**

* Lizmap Web Client : 3.7.10
* Lizmap plugin : 4.3.22
* QGIS Desktop : 3.22.16
* QGIS Server : 3.22.16
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.4.1
* QGIS Server plugin cadastre : 1.19.2
* QGIS Server plugin lizmap_server : 2.9.4
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : yes
* Number of parent : 2 folder(s)
* Prevent other drive : no
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

**Comment by Gustry** [comment]
Linked to recent work with 211a486ef2212b7b9d6167bac221d93962142e30, due to #597

This bug will happen on all LWC version.

**Comment by guenterw** [comment]
Yes, I have also tested it in the current 3.7, 3.8 and 3.9.

On Friday I searched quite a bit until I localised the error in the plugin. I have integrated many such WMS services in my projects. In future I should also install the updates of the QGIS plugin a little more carefully :)

**Comment by Gustry** [comment]
It will be fixed tonight

**Comment by guenterw** [comment]
Thank you very much for the super fast troubleshooting at the weekend. All 3 versions are working perfectly again.
