### ISSUE TITLE
tooltip limit layers

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-plugin#60]
hi

tooltip limit layers = 5
is it possible to increase the limite of available layers?

https://github.com/3liz/lizmap-web-client/issues/322

thanks

**Comment by josemvm** [comment]
hi @rldhont and @mdouchin,

i just want to remind you:

if it's possible and if you agree, i think it's an important feature to increase (or remove) the layers limit for the tooltip, in upcoming LWC 3.1.

thanks a lot

**Comment by mdouchin** [comment]
agree. We need to review the limits for differents tools and remove them if possible
