### ISSUE TITLE
What exactly  'Use extimated metadata' does on click button?

### ISSUE THREAD

**Issue by Antoviscomi** [3liz/lizmap-plugin#600]
@Gustry  I am trying to upload a postgis layer to my local server on an existing project via a python script, to publish it directly to an existing LWC project,
well, everything seems to be fine except for 'estimated metadata', I checked the difference between .cfg before and after clicking on 'estimated metadata' and no differences were found, so I am asking you what exactly this check does, to allow me to implement it via python script if it is possible.
thanks a lot in advance for your reply

**Comment by Gustry** [comment]
If you hold the mouse, as described at the top of table, you should have the information.
Or visit the "Help about checks".

Let me know

**Comment by Antoviscomi** [comment]
@Gustry on mouse hold I read of somewhat on connection string (but in general), here i meant, on what file or where the results og these corrections act
