### ISSUE TITLE
Active baselayer at startup - UnicodeEncodeError

### ISSUE THREAD

**Issue by igeofr** [3liz/lizmap-plugin#61]
Steps to reproduce
1. Ajout de la couche "Vue Aérienne 2009 40cm" depuis : http://ids.pigma.org/geoserver/wms
2. Configuration Lizmap : Flux en Fond de carte & Demander les images directement au serveur WMS
3. Choix du Fond de carte actif au démarrage
4. Enregistrement de la configuration

```
Traceback (most recent call last):
  File "C:/Users/_/.qgis2/python/plugins\lizmap\lizmap.py", line 2505, in getMapOptions
    self.writeProjectConfigFile()
  File "C:/Users/_/.qgis2/python/plugins\lizmap\lizmap.py", line 1996, in writeProjectConfigFile
    inputValue = str(inputValue)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 5: ordinal not in range(128)

```

lizmap version 2.1.1, QGIS 2.14.3-Essen on Windows 7

**Comment by Gustry** [comment]
@igeofr L'adresse WMS n'est plus valide. Est-ce qu'il y a une autre URL pour tester ce problème?

CC: @mdouchin ou @rldhont si vous avez une URL en tête. Je n'ai pas encore de QGIS server en test sur ma machine.

**Comment by igeofr** [comment]
@Gustry effectivement l'url a visiblement changé, mais il semble qu'il y ait une erreur : [https://www.pigma.org/geoserver/wms](https://www.pigma.org/geoserver/wms)
Pour faire le test, je propose d'utiliser le flux Géobretagne [http://geobretagne.fr/geoserver/wms?](http://geobretagne.fr/geoserver/wms?) et si c'est un problème d'accent, il est possible de faire le test avec la couche "IGN cartes scan25 et scan régional"

**Comment by Gustry** [comment]
Je ne peux pas répliquer le problème, cela semble marcher dans le plugin Lizmap.
Le passage à Python 3 dans QGIS 3 a certainement du aider. Est-ce possible de re-tester de votre côté?

**Comment by igeofr** [comment]
Idem, je viens de faire le test sur la 2.18 et je n'ai pas eu de message d'erreur. 
Je vais clore cette issue.
