### ISSUE TITLE
Localiser par couche ne fonctionne pas

### ISSUE THREAD

**Issue by griclo** [3liz/lizmap-plugin#64]
Avec les dernières versions lizmap plugin (2.1.2) et lizmap web client (3.0.3). 
Ca marchait trés bien quand j'étais sur le lizmap web client 2.12...

Je n'arrive pas à faire fonctionner l'outil correctement, il effectue un zoom trés fort sur un point qui ne correspond pas du tout à la couche indiquée. 
J'ai fait le test avec une ou deux couches ayant la même projection, le problème persiste.

**Comment by mbernasocchi** [comment]
je crois que le point ui est zomee est lis au low left edge et pas au milieu de la carte. en plus, ca se zoome jusq'au zoom plus forte.
@griclo pourrait tu confitmer?

**Comment by mbernasocchi** [comment]
en fait je croi que ce bug report devrait etre sur le web client

**Comment by mbernasocchi** [comment]
see https://github.com/3liz/lizmap-web-client/issues/397

**Comment by Gustry** [comment]
As requested by @mbernasocchi, I'm closing the issue.
