### ISSUE TITLE
UnicodeEncodeError in loadConfigInfoWidget

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-plugin#71]
In lizmap.py:881
`UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 11: ordinal not in range(128)`

![image002](https://cloud.githubusercontent.com/assets/1575538/22776135/cf05362e-eeae-11e6-8e87-73866b229391.jpg)

**Comment by rldhont** [comment]
@mdouchin can you take a look at this ?

**Comment by rldhont** [comment]
hi @ninsbl can you provide some example to help us fix this issue ?
Can you provide information about the operating system you use and the QGIS version ?

**Comment by Gustry** [comment]
High probability that this issue has been fixed by itself with Python3. Should we close it?

**Comment by Gustry** [comment]
I'm closing for lacking of feedbacks. Feel free to reopen if necessary or a new ticket.
