### ISSUE TITLE
metadata, abstract - missing html

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-plugin#72]
the abstract field loses the html code when plugin (re)loads the data from project

**Comment by fsdias** [comment]
Still true today.

This can be reproduced by:

- copy html text to a layer's metadata section

- open Lizmap plugin, go to "Layers" and click on the corresponding layer

- the html text is automatically converted to plain text

**Comment by arno974** [comment]
I have the same problem as well.

When adding HTML content into the abstract panel Lizmap sometimes looses the HTML markdown. It seems to be random as sometimes I am able to save and re-open Lizmap Plugin without loosing the HTML content.

**Comment by Gustry** [comment]
Does HTML is supported on the Lizmap Web client side? @mdouchin @rldhont @nboisteault 
To know if we should fix the HTML or to disable it?

**Comment by arno974** [comment]
Yes it is. Example : 
![image](https://user-images.githubusercontent.com/425243/63765383-f1b2dc00-c8d9-11e9-93ae-e661c0d53167.png)

**Comment by Gustry** [comment]
Fixed 2d2dd50

**Comment by josemvm** [comment]
@Gustry thanks a lot! 👍
