### ISSUE TITLE
Call geojson layer in lizmap

### ISSUE THREAD

**Issue by Strappy74** [3liz/lizmap-plugin#78]
Hi,

I am trying to call a public geojson layer in lizmap (Vigicrues water unit) with a public URL (by adding a vector layer as a protocol and not a file in QGIS) but when I click on the lizmap plugin in QGIS, I got a warning indicating that all layers have to be stored in the same file so I guess my geojson connexion is not recognized.

Here is the qlr code of the geojson layer (to open with Notepad +++)

[TRONCON_VIGICRUES.txt](https://github.com/3liz/lizmap-plugin/files/1041071/TRONCON_VIGICRUES.txt)

Thanks by advance for your help

**Comment by Gustry** [comment]
This check has been improved.
So is this issue still valid ?

**Comment by Gustry** [comment]
CLosing for lack of feedback.

There were a lot of improvments on this side.
