### ISSUE TITLE
popup

### ISSUE THREAD

**Issue by nepileptik** [3liz/lizmap-plugin#79]
Bonjour à vous; 
Je rencontre un problème avec mes popups, sur mon projet je souhaite faire apparaitre un popup pour une couche de point, et pour une couche de linéaire, mon problème est que ma couche de ponctuel affiche très bien mon popup mais ma couche de linéaire refuse de m'afficher le popup dans le mini dock le message suivant apparait :" aucune donnée a cet emplacement "

**Comment by mdouchin** [comment]
Avez-vous bien activé la popup pour la couche de lignes ?
Quelle est la valeur pour l'option "Tolérance pour l'interrogation des popups" pour les lignes ?
Si vous avez un lien public pour accéder au projet, cela permet souvent de voir et comprendre le souci

**Comment by nepileptik** [comment]
je suis désolé de répondre si tardivement mais j'avais posté la même question sur plusieurs site internet et j'avais oublié de clôturer ici mais j'ai fini par résoudre mon problème, j'ai redémarré mon serveur apache lors du redémarrage je pense qu'il doit y avoir un nettoyage des anciennes données et donc les popups refonctionnes... merci pour ton aide et désolé encore de ne pas avoir fermé la conversation

**Comment by mdouchin** [comment]
Aucun souci !
