### ISSUE TITLE
[Edition] Verifying that the primary keys are published in WFS

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-plugin#82]
The primary keys have to be published in WFS to be used in edition even if these fields are not displayed.

**Comment by Gustry** [comment]
Linked to #451

**Comment by Gustry** [comment]
Sorry, reopening here.

Edition doesn't ask the primary key of the layer, so the PR #553 was not fixing this ticket.

See edition definitions : https://github.com/3liz/lizmap-plugin/blob/master/lizmap/definitions/edition.py

I guess, PK should always be in WFS : according to specifications in #451 AND edition AND popup enabled ?

**Comment by Gustry** [comment]
I guess I can close here, I have added the PK for editing capabilities @rldhont and @mdouchin
