### ISSUE TITLE
LIZMAP Problème d'affichage de mes points

### ISSUE THREAD

**Issue by ronankerbi** [3liz/lizmap-plugin#84]
Bonjour,

dans l'utilisation de lizmap web client je rencontre des problèmes d'affichage de ma couche point. Mon problème lorsque je zoome mes points ne se charge pas je me retrouve avec un gros points flou au milieu de l'écran. Ce problème se rencontre toujours au même seuil de zoom. Donc j'ai essayé d'en supprimer mais cela persiste. Je ne sais si cela vient d'un bug de lizmap ou si j'ai un paramètre qui n'est pas bon. Voici une illustration de mon problème. 
![image](https://user-images.githubusercontent.com/23736561/32419315-5186a234-c278-11e7-84e9-4d78f1ba316a.png)
Je vous remercie par avance de l'aide que vous pourrez m'apporter.

Ronan

**Comment by josemvm** [comment]
hi @ronankerbi 

this is a lizmap-web-client issue, not a lizmap-plugin issue...
you can close it and open here https://github.com/3liz/lizmap-web-client/issues

**Comment by Gustry** [comment]
@josemvm is correct. This is wrong repository.
