### ISSUE TITLE
The legend is not displayed if 'Show total items' is set. 

### ISSUE THREAD

**Issue by news24lor** [3liz/lizmap-plugin#89]
I have a problem with the Legend. It is not displayed if 'Show total items' is set. This setting will crash Lizmap totally and after I have to restart Apache. The legend is displayed in Lizmap in normal way. Is this a bug? Is it possible to have 'Show total items' also in the Legend?
This is a useful feature in QGIS and also in Lizmap, if it work.
Thanks

**Comment by Gustry** [comment]
Are you talking about the `Show feature count`?
