### ISSUE TITLE
Qgis 3.0 - LIZMAP incompatible version

### ISSUE THREAD

**Issue by opbernardo** [3liz/lizmap-plugin#91]
Hi, 

I use the latest version on Qgis 3.0.0, and I dont have the icon from LIZMAP...

When I tried to install the zip file "lizmap-2.3.0.zip" I receive this message:

This plugin is incompatible with this version of QGIS,  Plugin designed for QGIS 2.0 - 2.99!

Are you going to do some LIZMAP update for the 3.0.0 version of QGIS?

Thanks for your help.

Sincerely.

Orlando

![lizmap_error](https://user-images.githubusercontent.com/15649016/36893986-e7ee889c-1e01-11e8-9454-3199d936da98.png)

I cant install the Lizmap Web Client 3.0 version, in my computer, do you have a manual in Portuguese?

P.S. My PC: windows 7 64 bit; 8 Gb Ram; 500Gb HDD disk

**Comment by opbernardo** [comment]
Hi jlstanus,
Thank you for your help.

**Comment by rldhont** [comment]
@mdouchin ha started some work to port the plugin to QGIS 3

**Comment by opbernardo** [comment]
Hi rldhont,
Do you have any time estimates for port the plugin to QGIS 3?
Thank you very much.

**Comment by mdouchin** [comment]
Please test the branch master_3 and reporte here any issue
https://github.com/3liz/lizmap-plugin/tree/master_3

I will publish a new version soon if no issue is reported. Be aware this master_3 version is based on the master branch, so it has features only available in the future Lizmap Web Client 3.2

@pcav @slarosa please test if you have time

**Comment by opbernardo** [comment]
Hi mdouchin,
I try to install the files I download from your link(https://github.com/3liz/lizmap-plugin/tree/master_3)
The plugin install correctly, but no icon apears, and give one error...
I send to you some pictures.
My OS in my pc is Windows 7 64 bit.
Thank you for your help.
Orlando
![01](https://user-images.githubusercontent.com/15649016/37142238-66e33c22-22af-11e8-9719-b707852d0073.png)
![02](https://user-images.githubusercontent.com/15649016/37142239-670645e6-22af-11e8-94eb-d482771872fe.png)
![03](https://user-images.githubusercontent.com/15649016/37142240-6728852a-22af-11e8-9463-2ff85476ff76.png)
![04](https://user-images.githubusercontent.com/15649016/37142241-674832c6-22af-11e8-867a-fdbe50ccff4b.png)

**Comment by mdouchin** [comment]
Please try again by downloading a fresh version of the ZIP. I have just added `qgisMaximumVersion=3.99` in the plugin metadata file

**Comment by opbernardo** [comment]
Hi again,
Now I just install the plugin without problem.
The icon works fine.
I go test with a project and I give you the feedback.
Thank you
Orlando

**Comment by opbernardo** [comment]
Hi mdouchin,
Everything works fine!
I tested and I dont find any type off errors or messages.
Thank you.
Is it possible, you create a LIZMAP.zip file, like the others versions (old), for Qgis?
Is more easy to install the LIZMAP 3.0 (now to install the 3.0 version is complicated).
Thank you for your support.

**Comment by shock82** [comment]
Hi mdouchin,
I've installed the master_3 plugin into QGIS 3.0, but when I try to open the popup window I receive this error message:
http://bit.ly/2GDcyHC
I've a wrong version of python?

Thanks in advance for your support.

**Comment by Gustry** [comment]
@camillemonchicourt I'm also testing QGIS 3. I made this quick PR about your error, I got it too: https://github.com/3liz/lizmap-plugin/pull/95

**Comment by camillemonchicourt** [comment]
Thanks.

**Comment by mdouchin** [comment]
Attention à tous. J'ai poussé la version compatible QGIS 3 sur la branche master

* la branche master reste donc la branche de développement principale, mais n'est plus compatible QGIS 2
* la branche qgis2 est la branche qui reste compatible avec QGIS 2 et qui permettra de faire de simple corrections de bugs

**Comment by opbernardo** [comment]
I mdouchin,

I have installed in my computer "Windows 7, 64 Bit", Qgis 2.18.23 from (OSGeo4W), "Lizmap web client 2.12.7", and "lizmap-plugin-qgis2" (lm) om my folder (C:\OSGeo4W\apache\htdocs\lm\...).

In browser "http://localhost/lm/lizmap/www/index.php/view/map/?repository=internet&project=teste_qgis", when I select from (Locating) a District and City (Mirandela), go to another place...

Am I doing something wrong?

Thank you for your help.

Best regards.

Orlando

**Comment by Gustry** [comment]
This should now be fixed. Feel free to reopen if the bug happens again.

@opbernardo Create a separate issue please.
