### ISSUE TITLE
Lizmap Web Client 3.0 

### ISSUE THREAD

**Issue by opbernardo** [3liz/lizmap-plugin#92]
Hi,

I cant install the Lizmap Web Client 3.0 version, in my computer, do you have a manual in Portuguese?

P.S. My PC: windows 7 64 bit; 8 Gb Ram; 500Gb HDD disk

Thank you for your help.

Orlando

**Comment by josemvm** [comment]
hi @opbernardo 

download the plugin zip file here: https://github.com/3liz/lizmap-plugin/tree/master_3
in QGIS 3, Manage and Install Plugins, choose `Install from ZIP`

it should work!

**Comment by opbernardo** [comment]
Hi josemvm,
My problem is to install LIZMAP (late version) inside "C:\OSGeo4W\apache\htdocs\lm\lizmap"  and see maps on internet.
The manual in english, give some errors on installation...
Thank you.

**Comment by josemvm** [comment]
see here: https://docs.3liz.com/pt/install/windows.html?highlight=windows

**Comment by opbernardo** [comment]
Hi josemvm,
Thank you!

**Comment by jonnyforestGIS** [comment]
@josemvm @opbernardo this can be close? If not @rldhont or @josemvm can you create a specific label for questions?

Cheers
João

**Comment by josemvm** [comment]
Hi @jonnyforestGIS 

this is an issue not belonging to this repository but solved. i think it can be closed

**Comment by jonnyforestGIS** [comment]
Yes i saw. This is an issue of webclient. If you have permissions in my opinion is better to close this. Cheers

**Comment by josemvm** [comment]
i have no rights to do it @jonnyforestGIS
