### ISSUE TITLE
A useful option for more security

### ISSUE THREAD

**Issue by news24lor** [3liz/lizmap-plugin#94]
I use the maps embedded in the web page.
In the list of lizmap options you have entered the possibility to hide many features of lizmap such as the menu bar, legend and more.
I would like you to include this new option:

`Hide info from the menu bar`

With this option on the map would remain only the choice of the layer, as in OpenLayers and does not offer the visitor information on how to connect to the WMS server of QGIS.

Thanks

**Comment by mdouchin** [comment]
We could indeed add an option to hide some menu, such as the information panel.

FYI, you can already remove the WMS/WMTS links from the information panel by unchecking the corresponding right in each repository configuration form (administration panel)

**Comment by news24lor** [comment]
That is true, I had not noticed it. Thank you for your information.
This option is now less useful.

Since the maps embedded in the page are small it is important to save space so hide everything (an option in your plugin) or see only the icon of the layers to choose from, easier to use for users. .
Currently there is only one bug when I select layers: the second window with transparencies goes under the layers window and therefore unusable. This bug is part of the web-client side, however.

Thanks again

**Comment by Gustry** [comment]
I think I'm closing this issue.
It's also possible to hide with a small javascript script.
